FUNCTION /1BEA/CRMB_DL_CRT_O_DOC_SET.
*"--------------------------------------------------------------------
*"*"Local Interface:
*"  IMPORTING
*"     REFERENCE(IS_DLI_WRK) TYPE  /1BEA/S_CRMB_DLI_WRK
*"--------------------------------------------------------------------
*======================================================================
*
* The following coding has been generated. Please do not change
* manually. All modifications will be lost by new generation.
*
* The code generation was triggered by
*
* Name  : DDIC
* Date  : 03.05.2012
* Time  : 13:53:10
*
*======================================================================
 CONSTANTS:
   LC_DIR_01            TYPE CRMT_TAX_DIRECTION_IND      VALUE '01',
   LC_WITHOUT_REG       TYPE CRMT_TAX_REGION_INDICATOR   VALUE 'X',
   LC_INV               TYPE TTET_BUSTRANSACTION_PD      VALUE 'INV',
   LC_CRM_FINANCE       TYPE CHAR11                      VALUE 'CRM_FINANCE'.

 DATA:
   LV_BILL_ORG          TYPE BU_PARTNER,
   LV_BILL_ORG_G        TYPE BU_PARTNER_GUID,
   LV_CRM_ITEM_TYPE     TYPE CRMT_ITEM_TYPE,
   LS_CRM_ITEM_TYPE     TYPE CRMC_ITEM_TYPE,
   LV_PD_HANDLE         TYPE PRCT_HANDLE,
   LS_CRT_HEADER        TYPE CRMT_TAX_HEADER_DATA,
   LS_CRT_ITEM          TYPE CRMT_TAX_ITEM_LIST,
   LT_CRT_ITEM          TYPE CRMT_TAX_ITEM_LIST_TAB.

 CHECK NOT IS_DLI_WRK-PRC_SESSION_ID IS INITIAL.

 CALL FUNCTION 'BEA_PRC_O_HNDL_GET'
   EXPORTING
     IV_SESSION_ID     = IS_DLI_WRK-PRC_SESSION_ID
   IMPORTING
     EV_PRICING_HANDLE = LV_PD_HANDLE
   EXCEPTIONS
     OTHERS            = 0.
 CHECK NOT LV_PD_HANDLE IS INITIAL.

 LV_BILL_ORG = IS_DLI_WRK-BILL_ORG.
 CALL FUNCTION 'COM_PARTNER_CONVERT_GUID_TO_NO'
   EXPORTING
     IV_PARTNER       = LV_BILL_ORG
   IMPORTING
     EV_PARTNER_GUID  = LV_BILL_ORG_G
   EXCEPTIONS
     OTHERS           = 0.

LS_CRT_HEADER-OWN_BUS_PARTNER = LV_BILL_ORG_G.

LS_CRT_ITEM-BILLING_UNIT = LV_BILL_ORG_G.
LS_CRT_ITEM-WITHOUT_REGION = LC_WITHOUT_REG.
  MOVE IS_DLI_WRK-RENDERED_DATE TO LS_CRT_ITEM-RENDERED_DATE.
  MOVE IS_DLI_WRK-SERVICE_ORG TO LS_CRT_ITEM-SERVICE_ORG.
  MOVE IS_DLI_WRK-PRODUCT TO LS_CRT_ITEM-PRODUCT_GUID.
  MOVE IS_DLI_WRK-DLI_GUID TO LS_CRT_ITEM-ITEM_GUID.
  MOVE IS_DLI_WRK-SALES_ORG TO LS_CRT_ITEM-SALES_ORG.
  MOVE IS_DLI_WRK-TAX_DEST_COUNTRY TO LS_CRT_ITEM-TAX_DEST_CTY.
  MOVE IS_DLI_WRK-INCOTERMS1 TO LS_CRT_ITEM-INCOTERMS1.
  MOVE IS_DLI_WRK-INCOTERMS2 TO LS_CRT_ITEM-INCOTERMS2.
  MOVE IS_DLI_WRK-SRC_ITEMNO TO LS_CRT_ITEM-POS_NUM.

 LS_CRT_ITEM-OBJECT_TYPE = GC_BOR_DLI.
 LV_CRM_ITEM_TYPE = IS_DLI_WRK-SRC_ITEM_TYPE.
 CALL FUNCTION 'CRM_ORDER_ITEM_TYPE_SELECT_CB'
   EXPORTING
     IV_ITEM_TYPE = LV_CRM_ITEM_TYPE
   IMPORTING
     ES_ITEM_TYPE = LS_CRM_ITEM_TYPE
   EXCEPTIONS
     OTHERS       = 0.
 LS_CRT_ITEM-BOR_OBJECT_TYPE = LS_CRM_ITEM_TYPE-OBJECT_TYPE.
 IF LS_CRT_ITEM-DIRECTION_IND IS INITIAL.
   LS_CRT_ITEM-DIRECTION_IND   = LC_DIR_01.
 ENDIF.
 IF IS_DLI_WRK-BUSINESSSCENARIO EQ GC_SCENARIO_FINANCE.
   LS_CRT_ITEM-BUS_SCENARIO = LC_CRM_FINANCE.
 ENDIF.
* Event _CRTDSI0
  INCLUDE %2f1BEA%2fX_CRMB_CRTDSI0_DSODL_MFA.
 APPEND LS_CRT_ITEM TO LT_CRT_ITEM.

 CALL FUNCTION 'CRM_TAX_TTE_DOCUMENT_SET'
   EXPORTING
     IV_PD_HANDLE             = LV_PD_HANDLE
     IS_HEADER_DATA           = LS_CRT_HEADER
     IT_ITEM_LIST             = LT_CRT_ITEM
     IV_BUSTRANSACTION        = LC_INV
     IV_BEA_APPLICATION       = 'CRMB'
   EXCEPTIONS
     OTHERS                   = 0.

ENDFUNCTION.
