*****************************************************************
*   THIS FILE IS GENERATED BY THE FUNCTION LIBRARY.             *
*   NEVER CHANGE IT MANUALLY, PLEASE!                           *
*****************************************************************
INCLUDE %2f1BEA%2fLCRMB_DL_PU01.
                    "/1BEA/CRMB_DL_P_POST
