*****************************************************************
*   THIS FILE IS GENERATED BY THE FUNCTION LIBRARY.             *
*   NEVER CHANGE IT MANUALLY, PLEASE!                           *
*****************************************************************
INCLUDE %2f1BEA%2fLCRMB_DL_TXT_OU01.
                    "/1BEA/CRMB_DL_TXT_O_COPY
INCLUDE %2f1BEA%2fLCRMB_DL_TXT_OU02.
                    "/1BEA/CRMB_DL_TXT_O_CREATE
INCLUDE %2f1BEA%2fLCRMB_DL_TXT_OU03.
                    "/1BEA/CRMB_DL_TXT_O_DELETE
INCLUDE %2f1BEA%2fLCRMB_DL_TXT_OU04.
                    "/1BEA/CRMB_DL_TXT_O_GET
INCLUDE %2f1BEA%2fLCRMB_DL_TXT_OU05.
                    "/1BEA/CRMB_DL_TXT_O_PROVIDE
INCLUDE %2f1BEA%2fLCRMB_DL_TXT_OU06.
                    "/1BEA/CRMB_DL_TXT_O_PUT
INCLUDE %2f1BEA%2fLCRMB_DL_TXT_OU07.
                    "/1BEA/CRMB_DL_TXT_O_READ
INCLUDE %2f1BEA%2fLCRMB_DL_TXT_OU08.
                    "/1BEA/CRMB_DL_TXT_O_REFRESH
INCLUDE %2f1BEA%2fLCRMB_DL_TXT_OU09.
                    "/1BEA/CRMB_DL_TXT_O_SAVE
