*****************************************************************
*   THIS FILE IS GENERATED BY THE FUNCTION LIBRARY.             *
*   NEVER CHANGE IT MANUALLY, PLEASE!                           *
*****************************************************************
INCLUDE %2f1BEA%2fLCRMB_BD_CRT_OU01.
                    "/1BEA/CRMB_BD_CRT_O_DOC_GET
INCLUDE %2f1BEA%2fLCRMB_BD_CRT_OU02.
                    "/1BEA/CRMB_BD_CRT_O_DOC_SET
INCLUDE %2f1BEA%2fLCRMB_BD_CRT_OU03.
                    "/1BEA/CRMB_BD_CRT_O_IT_COPY
INCLUDE %2f1BEA%2fLCRMB_BD_CRT_OU04.
                    "/1BEA/CRMB_BD_CRT_O_REFRESH
INCLUDE %2f1BEA%2fLCRMB_BD_CRT_OU05.
                    "/1BEA/CRMB_BD_CRT_O_SAVE
INCLUDE %2f1BEA%2fLCRMB_BD_CRT_OU06.
                    "/1BEA/CRMB_BD_CRT_O_SET_ARCHFL
