FUNCTION /1BEA/CRMB_DL_O_ENQUEUE.
*"--------------------------------------------------------------------
*"*"Local Interface:
*"  IMPORTING
*"     REFERENCE(IS_DLI_WRK) TYPE  /1BEA/S_CRMB_DLI_WRK
*"     REFERENCE(IV_X_DERIV_CATEGORY) TYPE  BEA_BOOLEAN OPTIONAL
*"     REFERENCE(IV_X_DERIV_COUNT) TYPE  BEA_BOOLEAN OPTIONAL
*"  EXPORTING
*"     REFERENCE(ES_RETURN) TYPE  BEAS_RETURN
*"--------------------------------------------------------------------
*======================================================================
*
* The following coding has been generated. Please do not change
* manually. All modifications will be lost by new generation.
*
* The code generation was triggered by
*
* Name  : DDIC
* Date  : 03.05.2012
* Time  : 13:53:10
*
*======================================================================
 DATA:
   LV_MSGV        TYPE SYMSGV,
   LV_LEVEL       TYPE SYMSGV,
   LV_USER        TYPE SYMSGV,
   LV_AL1ENQ      TYPE BEA_BOOLEAN,
   LS_ENQUEUE_DLI TYPE TY_ENQUEUE_DLI,
   LS_SRCDLHD_ENQ TYPE /1BEA/US_CRMB_DL_DLI_SRCDLHD,
   LV_X_DERIV_CATEGORY TYPE BEA_BOOLEAN VALUE 'X',
   LV_X_LOGSYS TYPE BEA_BOOLEAN VALUE 'X',
   LV_X_OBJTYPE TYPE BEA_BOOLEAN VALUE 'X',
   LV_X_SRC_HEADNO TYPE BEA_BOOLEAN VALUE 'X',
   LV_X_SRC_ITEMNO TYPE BEA_BOOLEAN VALUE 'X',
   LS_DG_ID_ENQ     TYPE /1BEA/US_CRMB_DL_DLI_DG_ID,
   LT_RETURN      TYPE BEAT_RETURN,
   LS_DLI_WRK     TYPE /1BEA/S_CRMB_DLI_WRK.

 IF IV_X_DERIV_CATEGORY IS INITIAL.
   LV_X_DERIV_CATEGORY = IV_X_DERIV_CATEGORY.
 ENDIF.

 IF (
    NOT IS_DLI_WRK-LOGSYS IS INITIAL
   AND NOT IS_DLI_WRK-OBJTYPE IS INITIAL
   AND NOT IS_DLI_WRK-SRC_HEADNO IS INITIAL
     ).
   LV_AL1ENQ = 'X'.
   READ TABLE GT_SRCDLHD_ENQ TRANSPORTING NO FIELDS WITH TABLE KEY
     DERIV_CATEGORY = IS_DLI_WRK-DERIV_CATEGORY
     LOGSYS = IS_DLI_WRK-LOGSYS
     OBJTYPE = IS_DLI_WRK-OBJTYPE
     SRC_HEADNO = IS_DLI_WRK-SRC_HEADNO.
   IF SY-SUBRC NE 0.
     LS_DLI_WRK-DERIV_CATEGORY = IS_DLI_WRK-DERIV_CATEGORY.
     LS_SRCDLHD_ENQ-DERIV_CATEGORY = IS_DLI_WRK-DERIV_CATEGORY.
     LS_DLI_WRK-LOGSYS = IS_DLI_WRK-LOGSYS.
     LS_SRCDLHD_ENQ-LOGSYS = IS_DLI_WRK-LOGSYS.
     LS_DLI_WRK-OBJTYPE = IS_DLI_WRK-OBJTYPE.
     LS_SRCDLHD_ENQ-OBJTYPE = IS_DLI_WRK-OBJTYPE.
     LS_DLI_WRK-SRC_HEADNO = IS_DLI_WRK-SRC_HEADNO.
     LS_SRCDLHD_ENQ-SRC_HEADNO = IS_DLI_WRK-SRC_HEADNO.
   ENDIF.
 ENDIF.

 IF (
    NOT IS_DLI_WRK-LOGSYS IS INITIAL
   AND NOT IS_DLI_WRK-OBJTYPE IS INITIAL
   AND NOT IS_DLI_WRK-SRC_HEADNO IS INITIAL
   AND NOT IS_DLI_WRK-SRC_ITEMNO IS INITIAL
     ).
   LV_LEVEL = TEXT-001.
   LV_AL1ENQ = 'X'.
   READ TABLE GT_DG_ID_ENQ TRANSPORTING NO FIELDS WITH TABLE KEY
     LOGSYS = IS_DLI_WRK-LOGSYS
     OBJTYPE = IS_DLI_WRK-OBJTYPE
     SRC_HEADNO = IS_DLI_WRK-SRC_HEADNO
     SRC_ITEMNO = IS_DLI_WRK-SRC_ITEMNO.
   IF SY-SUBRC NE 0.
     LS_DLI_WRK-LOGSYS = IS_DLI_WRK-LOGSYS.
     LS_DG_ID_ENQ-LOGSYS = IS_DLI_WRK-LOGSYS.
     LS_DLI_WRK-OBJTYPE = IS_DLI_WRK-OBJTYPE.
     LS_DG_ID_ENQ-OBJTYPE = IS_DLI_WRK-OBJTYPE.
     LS_DLI_WRK-SRC_HEADNO = IS_DLI_WRK-SRC_HEADNO.
     LS_DG_ID_ENQ-SRC_HEADNO = IS_DLI_WRK-SRC_HEADNO.
     LS_DLI_WRK-SRC_ITEMNO = IS_DLI_WRK-SRC_ITEMNO.
     LS_DG_ID_ENQ-SRC_ITEMNO = IS_DLI_WRK-SRC_ITEMNO.
   ENDIF.
 ENDIF.


 IF LS_DLI_WRK IS INITIAL.
   IF LV_AL1ENQ IS INITIAL.
     MESSAGE E226(BEA) WITH GC_P_DLI_HEADNO INTO GV_DUMMY.
     CALL FUNCTION '/1BEA/CRMB_DL_O_MESSAGE_ADD'
       EXPORTING
         IV_CONTAINER   = 'DLI'
         IS_DLI_WRK     = IS_DLI_WRK
       IMPORTING
         ET_RETURN      = LT_RETURN.
     READ TABLE LT_RETURN INTO ES_RETURN INDEX 1.
     RETURN.
   ELSE.
     RETURN.
   ENDIF.
 ENDIF.

* Insert into the global enqueue buffer
 LS_ENQUEUE_DLI-DERIV_CATEGORY = LS_DLI_WRK-DERIV_CATEGORY.
 LS_ENQUEUE_DLI-X_DERIV_CATEGORY = LV_X_DERIV_CATEGORY.
 LS_ENQUEUE_DLI-LOGSYS = LS_DLI_WRK-LOGSYS.
 LS_ENQUEUE_DLI-X_LOGSYS = LV_X_LOGSYS.
 LS_ENQUEUE_DLI-OBJTYPE = LS_DLI_WRK-OBJTYPE.
 LS_ENQUEUE_DLI-X_OBJTYPE = LV_X_OBJTYPE.
 LS_ENQUEUE_DLI-SRC_HEADNO = LS_DLI_WRK-SRC_HEADNO.
 LS_ENQUEUE_DLI-X_SRC_HEADNO = LV_X_SRC_HEADNO.
 LS_ENQUEUE_DLI-SRC_ITEMNO = LS_DLI_WRK-SRC_ITEMNO.
 LS_ENQUEUE_DLI-X_SRC_ITEMNO = LV_X_SRC_ITEMNO.
 IF LS_ENQUEUE_DLI IS NOT INITIAL.
   INSERT LS_ENQUEUE_DLI INTO TABLE GT_ENQUEUE_DLI.
 ENDIF.

 CALL FUNCTION 'ENQUEUE_/1BEA/ECRMB_DLI'
   EXPORTING
     DERIV_CATEGORY     = LS_DLI_WRK-DERIV_CATEGORY
     X_DERIV_CATEGORY   = LV_X_DERIV_CATEGORY
     LOGSYS     = LS_DLI_WRK-LOGSYS
     X_LOGSYS   = LV_X_LOGSYS
     OBJTYPE     = LS_DLI_WRK-OBJTYPE
     X_OBJTYPE   = LV_X_OBJTYPE
     SRC_HEADNO     = LS_DLI_WRK-SRC_HEADNO
     X_SRC_HEADNO   = LV_X_SRC_HEADNO
     SRC_ITEMNO     = LS_DLI_WRK-SRC_ITEMNO
     X_SRC_ITEMNO   = LV_X_SRC_ITEMNO
   EXCEPTIONS
     FOREIGN_LOCK   = 1
     SYSTEM_FAILURE = 2
     OTHERS         = 3.
 IF SY-SUBRC NE 0.
   LV_USER = SY-MSGV1.
   IF LV_LEVEL IS INITIAL.
     MESSAGE E240(BEA) WITH GC_P_DLI_HEADNO LV_USER
                       INTO GV_DUMMY.
   ELSE.
     MESSAGE E241(BEA) WITH LV_LEVEL GC_P_DLI_HEADNO
                            LV_USER
                       INTO GV_DUMMY.
   ENDIF.
   CALL FUNCTION '/1BEA/CRMB_DL_O_MESSAGE_ADD'
     EXPORTING
       IV_CONTAINER   = 'DLI'
       IS_DLI_WRK     = IS_DLI_WRK
     IMPORTING
       ET_RETURN      = LT_RETURN.
   READ TABLE LT_RETURN INTO ES_RETURN INDEX 1.
 ELSEIF NOT LS_SRCDLHD_ENQ IS INITIAL.
   INSERT LS_SRCDLHD_ENQ INTO TABLE GT_SRCDLHD_ENQ.
 ELSEIF NOT LS_DG_ID_ENQ IS INITIAL.
   INSERT LS_DG_ID_ENQ INTO TABLE GT_DG_ID_ENQ.
 ENDIF.


ENDFUNCTION.
