FUNCTION /1BEA/CRMB_DL_O_DLIGETLIST.
*"--------------------------------------------------------------------
*"*"Local Interface:
*"  IMPORTING
*"     REFERENCE(IV_DLH_GUID) TYPE  BEA_DLH_GUID
*"  EXPORTING
*"     REFERENCE(ET_DLI_WRK) TYPE  /1BEA/T_CRMB_DLI_WRK
*"     REFERENCE(EV_DLH_MODIFIED) TYPE  BEA_BOOLEAN
*"  EXCEPTIONS
*"      NOTFOUND
*"--------------------------------------------------------------------
*======================================================================
*
* The following coding has been generated. Please do not change
* manually. All modifications will be lost by new generation.
*
* The code generation was triggered by
*
* Name  : DDIC
* Date  : 03.05.2012
* Time  : 13:53:10
*
*======================================================================
 FIELD-SYMBOLS:
  "<ls_dlh_wrk>        TYPE /1bea/s_CRMB_DLI_wrk,
  <ls_dli_wrk>        TYPE /1bea/s_CRMB_DLI_wrk.
 DATA:
   LS_DLH_WRK         LIKE LINE OF GT_DLH_WRK.
 DATA: LRT_DLI_BILL_BLOCK TYPE BEART_BILL_BLOCK.
 DATA: LRS_DLI_BILL_BLOCK LIKE LINE OF LRT_DLI_BILL_BLOCK.
 DATA: LRT_DLI_BILL_STATUS TYPE BEART_BILL_STATUS.
 DATA: LRS_DLI_BILL_STATUS LIKE LINE OF LRT_DLI_BILL_STATUS.
 DATA: LRT_DLI_INCOMP_ID TYPE BEART_INCOMP_ID.
 DATA: LRS_DLI_INCOMP_ID LIKE LINE OF LRT_DLI_INCOMP_ID.


READ TABLE GT_DLH_WRK INTO LS_DLH_WRK
      WITH TABLE KEY DLI_GUID = IV_DLH_GUID.
CHECK SY-SUBRC = 0.


  LOOP AT GT_DLI_WRK
      ASSIGNING <LS_DLI_WRK>
     WHERE
          DERIV_CATEGORY  = LS_DLH_WRK-DERIV_CATEGORY
         AND LOGSYS  = LS_DLH_WRK-LOGSYS
         AND OBJTYPE  = LS_DLH_WRK-OBJTYPE
         AND SRC_HEADNO  = LS_DLH_WRK-SRC_HEADNO.

    APPEND <ls_DLI_wrk> TO ET_DLI_WRK.

  ENDLOOP.

  IF ET_DLI_WRK IS INITIAL.
    DATA: LRT_DERIV_CATEGORY LIKE RANGE OF LS_DLH_WRK-DERIV_CATEGORY.
    DATA: LRS_DERIV_CATEGORY LIKE LINE OF LRT_DERIV_CATEGORY.
    LRS_DERIV_CATEGORY-SIGN = 'I'.
    LRS_DERIV_CATEGORY-OPTION = 'EQ'.
    LRS_DERIV_CATEGORY-LOW = LS_DLH_WRK-DERIV_CATEGORY.
    APPEND LRS_DERIV_CATEGORY TO LRT_DERIV_CATEGORY.

    DATA: LRT_LOGSYS LIKE RANGE OF LS_DLH_WRK-LOGSYS.
    DATA: LRS_LOGSYS LIKE LINE OF LRT_LOGSYS.
    LRS_LOGSYS-SIGN = 'I'.
    LRS_LOGSYS-OPTION = 'EQ'.
    LRS_LOGSYS-LOW = LS_DLH_WRK-LOGSYS.
    APPEND LRS_LOGSYS TO LRT_LOGSYS.

    DATA: LRT_OBJTYPE LIKE RANGE OF LS_DLH_WRK-OBJTYPE.
    DATA: LRS_OBJTYPE LIKE LINE OF LRT_OBJTYPE.
    LRS_OBJTYPE-SIGN = 'I'.
    LRS_OBJTYPE-OPTION = 'EQ'.
    LRS_OBJTYPE-LOW = LS_DLH_WRK-OBJTYPE.
    APPEND LRS_OBJTYPE TO LRT_OBJTYPE.

    DATA: LRT_SRC_HEADNO LIKE RANGE OF LS_DLH_WRK-SRC_HEADNO.
    DATA: LRS_SRC_HEADNO LIKE LINE OF LRT_SRC_HEADNO.
    LRS_SRC_HEADNO-SIGN = 'I'.
    LRS_SRC_HEADNO-OPTION = 'EQ'.
    LRS_SRC_HEADNO-LOW = LS_DLH_WRK-SRC_HEADNO.
    APPEND LRS_SRC_HEADNO TO LRT_SRC_HEADNO.


     LRS_DLI_BILL_STATUS-SIGN   = GC_INCLUDE.
     LRS_DLI_BILL_STATUS-OPTION = GC_EQUAL.
     LRS_DLI_BILL_STATUS-LOW    = GC_BILLSTAT_TODO.
     APPEND LRS_DLI_BILL_STATUS TO LRT_DLI_BILL_STATUS.
     LRS_DLI_INCOMP_ID-SIGN    = GC_INCLUDE.
     LRS_DLI_INCOMP_ID-OPTION  = GC_EQUAL.
     LRS_DLI_INCOMP_ID-LOW     = GC_INCOMP_OK.
     APPEND LRS_DLI_INCOMP_ID TO LRT_DLI_INCOMP_ID.

     CALL FUNCTION '/1BEA/CRMB_DL_O_DLGETKEYS'
       EXPORTING
         IRT_DLI_DERIV_CATEGORY         = LRT_DERIV_CATEGORY
         IRT_DLI_LOGSYS         = LRT_LOGSYS
         IRT_DLI_OBJTYPE         = LRT_OBJTYPE
         IRT_DLI_SRC_HEADNO         = LRT_SRC_HEADNO
         IRT_DLI_BILL_STATUS        = LRT_DLI_BILL_STATUS
         IRT_DLI_INCOMP_ID          = LRT_DLI_INCOMP_ID
         IV_DLH_GUID                = IV_DLH_GUID
       IMPORTING
         ET_DLI_WRK                 = ET_DLI_WRK
               .
    EV_DLH_MODIFIED = GC_TRUE.
  ENDIF.
ENDFUNCTION.
