*****************************************************************
*   THIS FILE IS GENERATED BY THE FUNCTION LIBRARY.             *
*   NEVER CHANGE IT MANUALLY, PLEASE!                           *
*****************************************************************
INCLUDE %2f1BEA%2fLCRMB_DL_PRC_OU01.
                    "/1BEA/CRMB_DL_PRC_O_COPY
INCLUDE %2f1BEA%2fLCRMB_DL_PRC_OU02.
                    "/1BEA/CRMB_DL_PRC_O_CREATE
INCLUDE %2f1BEA%2fLCRMB_DL_PRC_OU03.
                    "/1BEA/CRMB_DL_PRC_O_DELETE
INCLUDE %2f1BEA%2fLCRMB_DL_PRC_OU04.
                    "/1BEA/CRMB_DL_PRC_O_GET_INFO
INCLUDE %2f1BEA%2fLCRMB_DL_PRC_OU05.
                    "/1BEA/CRMB_DL_PRC_O_IT_MAPIN
INCLUDE %2f1BEA%2fLCRMB_DL_PRC_OU06.
                    "/1BEA/CRMB_DL_PRC_O_IT_MAPOUT
INCLUDE %2f1BEA%2fLCRMB_DL_PRC_OU07.
                    "/1BEA/CRMB_DL_PRC_O_OPEN
INCLUDE %2f1BEA%2fLCRMB_DL_PRC_OU08.
                    "/1BEA/CRMB_DL_PRC_O_PREPARE
INCLUDE %2f1BEA%2fLCRMB_DL_PRC_OU09.
                    "/1BEA/CRMB_DL_PRC_O_QTY_ADD
INCLUDE %2f1BEA%2fLCRMB_DL_PRC_OU10.
                    "/1BEA/CRMB_DL_PRC_O_REFRESH
INCLUDE %2f1BEA%2fLCRMB_DL_PRC_OU11.
                    "/1BEA/CRMB_DL_PRC_O_SAVE
