*======================================================================
*
* The following coding has been generated. Please do not change
* manually. All modifications will be lost by new generation.
*
* The code generation was triggered by
*
* Name  : DDIC
* Date  : 03.05.2012
* Time  : 13:53:02
*
*======================================================================
 CONSTANTS: LC_PRDODL_IOP_IOBJECT_ATTR TYPE PRCT_ATTR_NAME
              VALUE 'IOBJECT_GUID',
            LC_PRDODL_IOP_PRC_PRD_ATTR TYPE PRCT_ATTR_NAME
              VALUE 'PRICE_PRODUCT',
            LC_PRDODL_IOP_PRODUCT_ATTR TYPE PRCT_ATTR_NAME
              VALUE 'PRODUCT'.

 DATA:
   LV_PRDODL_IOP_REFPROD_GUID   TYPE COMT_PRODUCT_GUID,
   LS_PRDODL_IOP_ATTR_NAME_VALUE TYPE PRCT_ATTR_NAME_VALUE.

* Check if IOBJECT_GUID is requested.
 READ TABLE GT_ALL_ATTR_NAMES TRANSPORTING NO FIELDS
   WITH KEY TABLE_LINE = LC_PRDODL_IOP_IOBJECT_ATTR
   BINARY SEARCH.
 IF SY-SUBRC = 0.
   CALL FUNCTION 'COM_PRODUCT_GET_REFERENCE_PROD'
     EXPORTING
       IV_PRODUCT_GUID = LS_PRC_ITEM-MATNR
     IMPORTING
       EV_REFPROD_GUID = LV_PRDODL_IOP_REFPROD_GUID
     EXCEPTIONS
       WRONG_CALL      = 1
       INTERNAL_ERROR  = 2
       OTHERS          = 3.
   IF SY-SUBRC NE 0.
     MESSAGE ID SY-MSGID TYPE SY-MSGTY NUMBER SY-MSGNO
        WITH SY-MSGV1 SY-MSGV2 SY-MSGV3 SY-MSGV4 INTO GV_DUMMY.
     PERFORM MSG_ADD USING SPACE SPACE SPACE SPACE CHANGING ET_RETURN.
     MESSAGE ID SY-MSGID TYPE SY-MSGTY NUMBER SY-MSGNO
        WITH SY-MSGV1 SY-MSGV2 SY-MSGV3 SY-MSGV4 RAISING REJECT.
   ENDIF.

   IF NOT LV_PRDODL_IOP_REFPROD_GUID IS INITIAL.
     LS_PRDODL_IOP_ATTR_NAME_VALUE-ATTR_NAME  = LC_PRDODL_IOP_IOBJECT_ATTR.
     LS_PRDODL_IOP_ATTR_NAME_VALUE-ATTR_VALUE = LS_PRC_ITEM-MATNR.
     PERFORM FILL_ITEM_NAME_VALUE_TAB USING LS_PRDODL_IOP_ATTR_NAME_VALUE
                                            GC_TRUE
                                      CHANGING LS_PRC_ITEM.
* Fill the PRICE_PRODUCT, if requested.
     READ TABLE GT_ALL_ATTR_NAMES TRANSPORTING NO FIELDS
       WITH KEY TABLE_LINE = LC_PRDODL_IOP_PRC_PRD_ATTR
       BINARY SEARCH.
     IF SY-SUBRC = 0.
       READ TABLE LS_PRC_ITEM-ITEM_ATTRIBUTES INTO LS_PRDODL_IOP_ATTR_NAME_VALUE
         WITH KEY ATTR_NAME  = LC_PRDODL_IOP_PRC_PRD_ATTR
         BINARY SEARCH.
       IF SY-SUBRC EQ 0 AND
         LS_PRC_ITEM-MATNR EQ LS_PRDODL_IOP_ATTR_NAME_VALUE-ATTR_VALUE.
         LS_PRDODL_IOP_ATTR_NAME_VALUE-ATTR_VALUE = LV_PRDODL_IOP_REFPROD_GUID.
         PERFORM FILL_ITEM_NAME_VALUE_TAB USING LS_PRDODL_IOP_ATTR_NAME_VALUE
                                            GC_TRUE
                                      CHANGING LS_PRC_ITEM.
       ENDIF.
     ENDIF.
* Fill the PRODUCT, if requested.
     READ TABLE GT_ALL_ATTR_NAMES TRANSPORTING NO FIELDS
       WITH KEY TABLE_LINE = LC_PRDODL_IOP_PRODUCT_ATTR
       BINARY SEARCH.
     IF SY-SUBRC = 0.
       READ TABLE LS_PRC_ITEM-ITEM_ATTRIBUTES INTO LS_PRDODL_IOP_ATTR_NAME_VALUE
         WITH KEY ATTR_NAME  = LC_PRDODL_IOP_PRODUCT_ATTR
         BINARY SEARCH.
       LS_PRDODL_IOP_ATTR_NAME_VALUE-ATTR_NAME = LC_PRDODL_IOP_PRODUCT_ATTR.
       LS_PRDODL_IOP_ATTR_NAME_VALUE-ATTR_VALUE = LV_PRDODL_IOP_REFPROD_GUID.
       PERFORM FILL_ITEM_NAME_VALUE_TAB USING LS_PRDODL_IOP_ATTR_NAME_VALUE
                                              GC_TRUE
                                        CHANGING LS_PRC_ITEM.
     ENDIF.
   ENDIF.
 ENDIF.
