FUNCTION /1BEA/CRMB_BD_O_BDIGETLIST.
*"--------------------------------------------------------------------
*"*"Local Interface:
*"  IMPORTING
*"     REFERENCE(IRT_BDH_GUID) TYPE  BEART_BDH_GUID OPTIONAL
*"     REFERENCE(IRT_BDI_GUID) TYPE  BEART_BDI_GUID OPTIONAL
*"     REFERENCE(IRT_BILL_RELEVANCE) TYPE  BEART_BILL_RELEVANCE
*"         OPTIONAL
*"     REFERENCE(IRT_CREATION_CODE) TYPE  BEART_CREATION_CODE
*"         OPTIONAL
*"     REFERENCE(IRT_CREDIT_DEBIT) TYPE  BEART_CREDIT_DEBIT OPTIONAL
*"     REFERENCE(IRT_DIS_CHANNEL) TYPE  /1BEA/RT_CRMB_DIS_CHANNEL
*"         OPTIONAL
*"     REFERENCE(IRT_DIVISION) TYPE  /1BEA/RT_CRMB_DIVISION OPTIONAL
*"     REFERENCE(IRT_DOC_CURRENCY) TYPE  BEART_DOC_CURRENCY OPTIONAL
*"     REFERENCE(IRT_EXCHANGE_DATE) TYPE  BEART_EXCHANGE_DATE
*"         OPTIONAL
*"     REFERENCE(IRT_EXCHANGE_RATE) TYPE  BEART_EXCHANGE_RATE
*"         OPTIONAL
*"     REFERENCE(IRT_GROSS_VALUE) TYPE  BEART_GROSS_VALUE OPTIONAL
*"     REFERENCE(IRT_IS_REVERSED) TYPE  BEART_IS_REVERSED OPTIONAL
*"     REFERENCE(IRT_ITEMNO_EXT) TYPE  BEART_ITEMNO_EXT OPTIONAL
*"     REFERENCE(IRT_ITEM_CATEGORY) TYPE  BEART_ITEM_CATEGORY
*"         OPTIONAL
*"     REFERENCE(IRT_ITEM_TYPE) TYPE  BEART_ITEM_TYPE OPTIONAL
*"     REFERENCE(IRT_LOGSYS) TYPE  /1BEA/RT_CRMB_LOGSYS OPTIONAL
*"     REFERENCE(IRT_NET_VALUE) TYPE  BEART_NET_VALUE OPTIONAL
*"     REFERENCE(IRT_OBJTYPE) TYPE  /1BEA/RT_CRMB_OBJTYPE OPTIONAL
*"     REFERENCE(IRT_PARENT_ITEMNO) TYPE  /1BEA/RT_CRMB_PARENT_ITEMNO
*"         OPTIONAL
*"     REFERENCE(IRT_PRODUCT) TYPE  /1BEA/RT_CRMB_PRODUCT OPTIONAL
*"     REFERENCE(IRT_PRODUCT_DESCR) TYPE  /1BEA/RT_CRMB_PRODUCT_DESCR
*"         OPTIONAL
*"     REFERENCE(IRT_REVERSAL) TYPE  BEART_REVERSAL OPTIONAL
*"     REFERENCE(IRT_SALES_ORG) TYPE  /1BEA/RT_CRMB_SALES_ORG
*"         OPTIONAL
*"     REFERENCE(IRT_SERVICE_ORG) TYPE  /1BEA/RT_CRMB_SERVICE_ORG
*"         OPTIONAL
*"     REFERENCE(IRT_SRC_GUID) TYPE  /1BEA/RT_CRMB_SRC_GUID OPTIONAL
*"     REFERENCE(IRT_SRC_HEADNO) TYPE  /1BEA/RT_CRMB_SRC_HEADNO
*"         OPTIONAL
*"     REFERENCE(IRT_SRC_ITEMNO) TYPE  /1BEA/RT_CRMB_SRC_ITEMNO
*"         OPTIONAL
*"     REFERENCE(IRT_SRC_ITEM_TYPE) TYPE  /1BEA/RT_CRMB_SRC_ITEM_TYPE
*"         OPTIONAL
*"     REFERENCE(IRT_SRC_PROCESS_TYPE) TYPE
*"                             /1BEA/RT_CRMB_SRC_PROCESS_TYPE
*"         OPTIONAL
*"     REFERENCE(IRT_SRVDOC_SOURCE) TYPE  BEART_SRVDOC_SOURCE
*"         OPTIONAL
*"     REFERENCE(IRT_TAX_VALUE) TYPE  BEART_TAX_VALUE OPTIONAL
*"  EXPORTING
*"     REFERENCE(ET_BDI) TYPE  /1BEA/T_CRMB_BDI_WRK
*"--------------------------------------------------------------------
*======================================================================
*
* The following coding has been generated. Please do not change
* manually. All modifications will be lost by new generation.
*
* The code generation was triggered by
*
* Name  : DDIC
* Date  : 03.05.2012
* Time  : 13:52:50
*
*======================================================================

 FIELD-SYMBOLS:
    <LS_BDI_WRK>       TYPE /1BEA/S_CRMB_BDI_WRK.

 DATA:
   lv_read_db   TYPE bea_boolean,
   lv_BDI_guid  TYPE bea_BDI_guid,
   lt_BDI_guid  TYPE beat_BDI_guid,
   lrs_BDI_guid LIKE LINE OF irt_BDI_guid.

 CLEAR ET_BDI.
* First check in buffer, when BDI_GUIDs are provided
 IF irt_BDI_guid IS NOT INITIAL.
   lv_read_db = gc_false.
   LOOP AT irt_BDI_guid INTO lrs_BDI_guid.
     IF lrs_BDI_guid-option <> gc_equal.
       lv_read_db = gc_true.
       EXIT.
     ENDIF.
     INSERT lrs_BDI_guid-low INTO TABLE lt_BDI_guid.
   ENDLOOP.
   IF lv_read_db <> gc_true.
     LOOP AT lt_BDI_guid INTO lv_BDI_guid.
       READ TABLE gt_BDI_wrk ASSIGNING <ls_BDI_wrk>
         WITH KEY BDI_guid = lv_BDI_guid.
       IF sy-subrc <> 0.
         lv_read_db = gc_true.
         CLEAR et_bdi. EXIT.
       ELSE.
         APPEND <ls_BDI_wrk> TO et_bdi.
       ENDIF.
     ENDLOOP.
   ENDIF.
   CHECK lv_read_db = gc_true.
 ENDIF.
* Second check in buffer, when BDH_GUIDs are provided
  IF IRT_BDH_GUID IS NOT INITIAL.
    LOOP AT GT_BDI_WRK ASSIGNING <LS_BDI_WRK>
         WHERE
                  BDH_GUID IN IRT_BDH_GUID
                 AND BDI_GUID IN IRT_BDI_GUID
                 AND BILL_RELEVANCE IN IRT_BILL_RELEVANCE
                 AND CREATION_CODE IN IRT_CREATION_CODE
                 AND CREDIT_DEBIT IN IRT_CREDIT_DEBIT
                 AND DIS_CHANNEL IN IRT_DIS_CHANNEL
                 AND DIVISION IN IRT_DIVISION
                 AND DOC_CURRENCY IN IRT_DOC_CURRENCY
                 AND EXCHANGE_DATE IN IRT_EXCHANGE_DATE
                 AND EXCHANGE_RATE IN IRT_EXCHANGE_RATE
                 AND GROSS_VALUE IN IRT_GROSS_VALUE
                 AND IS_REVERSED IN IRT_IS_REVERSED
                 AND ITEMNO_EXT IN IRT_ITEMNO_EXT
                 AND ITEM_CATEGORY IN IRT_ITEM_CATEGORY
                 AND ITEM_TYPE IN IRT_ITEM_TYPE
                 AND LOGSYS IN IRT_LOGSYS
                 AND NET_VALUE IN IRT_NET_VALUE
                 AND OBJTYPE IN IRT_OBJTYPE
                 AND PARENT_ITEMNO IN IRT_PARENT_ITEMNO
                 AND PRODUCT IN IRT_PRODUCT
                 AND PRODUCT_DESCR IN IRT_PRODUCT_DESCR
                 AND REVERSAL IN IRT_REVERSAL
                 AND SALES_ORG IN IRT_SALES_ORG
                 AND SERVICE_ORG IN IRT_SERVICE_ORG
                 AND SRC_GUID IN IRT_SRC_GUID
                 AND SRC_HEADNO IN IRT_SRC_HEADNO
                 AND SRC_ITEMNO IN IRT_SRC_ITEMNO
                 AND SRC_ITEM_TYPE IN IRT_SRC_ITEM_TYPE
                 AND SRC_PROCESS_TYPE IN IRT_SRC_PROCESS_TYPE
                 AND SRVDOC_SOURCE IN IRT_SRVDOC_SOURCE
                 AND TAX_VALUE IN IRT_TAX_VALUE.
      APPEND <LS_BDI_WRK> TO ET_BDI.
    ENDLOOP.
  ENDIF.

* If there's no hit, read from DB
  CHECK ET_BDI IS INITIAL.
  SELECT * FROM /1BEA/CRMB_BDI
           INTO CORRESPONDING FIELDS OF TABLE ET_BDI
         WHERE
                  BDH_GUID IN IRT_BDH_GUID
                 AND BDI_GUID IN IRT_BDI_GUID
                 AND BILL_RELEVANCE IN IRT_BILL_RELEVANCE
                 AND CREATION_CODE IN IRT_CREATION_CODE
                 AND CREDIT_DEBIT IN IRT_CREDIT_DEBIT
                 AND DIS_CHANNEL IN IRT_DIS_CHANNEL
                 AND DIVISION IN IRT_DIVISION
                 AND DOC_CURRENCY IN IRT_DOC_CURRENCY
                 AND EXCHANGE_DATE IN IRT_EXCHANGE_DATE
                 AND EXCHANGE_RATE IN IRT_EXCHANGE_RATE
                 AND GROSS_VALUE IN IRT_GROSS_VALUE
                 AND IS_REVERSED IN IRT_IS_REVERSED
                 AND ITEMNO_EXT IN IRT_ITEMNO_EXT
                 AND ITEM_CATEGORY IN IRT_ITEM_CATEGORY
                 AND ITEM_TYPE IN IRT_ITEM_TYPE
                 AND LOGSYS IN IRT_LOGSYS
                 AND NET_VALUE IN IRT_NET_VALUE
                 AND OBJTYPE IN IRT_OBJTYPE
                 AND PARENT_ITEMNO IN IRT_PARENT_ITEMNO
                 AND PRODUCT IN IRT_PRODUCT
                 AND PRODUCT_DESCR IN IRT_PRODUCT_DESCR
                 AND REVERSAL IN IRT_REVERSAL
                 AND SALES_ORG IN IRT_SALES_ORG
                 AND SERVICE_ORG IN IRT_SERVICE_ORG
                 AND SRC_GUID IN IRT_SRC_GUID
                 AND SRC_HEADNO IN IRT_SRC_HEADNO
                 AND SRC_ITEMNO IN IRT_SRC_ITEMNO
                 AND SRC_ITEM_TYPE IN IRT_SRC_ITEM_TYPE
                 AND SRC_PROCESS_TYPE IN IRT_SRC_PROCESS_TYPE
                 AND SRVDOC_SOURCE IN IRT_SRVDOC_SOURCE
                 AND TAX_VALUE IN IRT_TAX_VALUE.

ENDFUNCTION.
