FUNCTION /1BEA/CRMB_BD_O_BDGETLIST.
*"--------------------------------------------------------------------
*"*"Local Interface:
*"  IMPORTING
*"     REFERENCE(IV_AUTH_CHECK) TYPE  BEA_BOOLEAN DEFAULT SPACE
*"     REFERENCE(IRT_BDH_ARCHIVABLE) TYPE  BEART_ARCHIVABLE OPTIONAL
*"     REFERENCE(IRT_BDH_BDH_GUID) TYPE  BEART_BDH_GUID OPTIONAL
*"     REFERENCE(IRT_BDH_BILL_CATEGORY) TYPE  BEART_BILL_CATEGORY
*"         OPTIONAL
*"     REFERENCE(IRT_BDH_BILL_DATE) TYPE  BEART_BILL_DATE OPTIONAL
*"     REFERENCE(IRT_BDH_BILL_ORG) TYPE  BEART_BILL_ORG OPTIONAL
*"     REFERENCE(IRT_BDH_BILL_TYPE) TYPE  BEART_BILL_TYPE OPTIONAL
*"     REFERENCE(IRT_BDH_CANCEL_FLAG) TYPE  BEART_CANCEL_FLAG
*"         OPTIONAL
*"     REFERENCE(IRT_BDH_CRP_GUID) TYPE  BEART_CRP_GUID OPTIONAL
*"     REFERENCE(IRT_BDH_DOC_CURRENCY) TYPE  BEART_DOC_CURRENCY
*"         OPTIONAL
*"     REFERENCE(IRT_BDH_HEADNO_EXT) TYPE  BEART_HEADNO_EXT OPTIONAL
*"     REFERENCE(IRT_BDH_LOGSYS) TYPE  BEART_LOGSYS OPTIONAL
*"     REFERENCE(IRT_BDH_MAINT_DATE) TYPE  BEART_MAINT_DATE OPTIONAL
*"     REFERENCE(IRT_BDH_MAINT_TIME) TYPE  BEART_MAINT_TIME OPTIONAL
*"     REFERENCE(IRT_BDH_MAINT_USER) TYPE  BEART_MAINT_USER OPTIONAL
*"     REFERENCE(IRT_BDH_NET_VALUE) TYPE  BEART_NET_VALUE OPTIONAL
*"     REFERENCE(IRT_BDH_OBJTYPE) TYPE  BEART_OBJTYPE OPTIONAL
*"     REFERENCE(IRT_BDH_PAYER) TYPE  BEART_PAYER OPTIONAL
*"     REFERENCE(IRT_BDH_PRIC_PROC) TYPE  BEART_PRIC_PROC OPTIONAL
*"     REFERENCE(IRT_BDH_REFERENCE_NO) TYPE  BEART_REFERENCE_NO
*"         OPTIONAL
*"     REFERENCE(IRT_BDH_REF_CURRENCY) TYPE  BEART_REF_CURRENCY
*"         OPTIONAL
*"     REFERENCE(IRT_BDH_SPLIT_CRITERIA) TYPE  BEART_SPLIT_CRITERIA
*"         OPTIONAL
*"     REFERENCE(IRT_BDH_TAX_VALUE) TYPE  BEART_TAX_VALUE OPTIONAL
*"     REFERENCE(IRT_BDH_TERMS_OF_PAYMENT) TYPE
*"                             BEART_TERMS_OF_PAYMENT OPTIONAL
*"     REFERENCE(IRT_BDH_TRANSFER_DATE) TYPE  BEART_TRANSFER_DATE
*"         OPTIONAL
*"     REFERENCE(IRT_BDH_TRANSFER_ERROR) TYPE
*"                             /1BEA/RT_CRMB_TRANSFER_ERROR OPTIONAL
*"     REFERENCE(IRT_BDH_TRANSFER_STATUS) TYPE  BEART_TRANSFER_STATUS
*"         OPTIONAL
*"     REFERENCE(IRT_BDI_BDH_GUID) TYPE  BEART_BDH_GUID OPTIONAL
*"     REFERENCE(IRT_BDI_BDI_GUID) TYPE  BEART_BDI_GUID OPTIONAL
*"     REFERENCE(IRT_BDI_BILL_RELEVANCE) TYPE  BEART_BILL_RELEVANCE
*"         OPTIONAL
*"     REFERENCE(IRT_BDI_CREATION_CODE) TYPE  BEART_CREATION_CODE
*"         OPTIONAL
*"     REFERENCE(IRT_BDI_CREDIT_DEBIT) TYPE  BEART_CREDIT_DEBIT
*"         OPTIONAL
*"     REFERENCE(IRT_BDI_DIS_CHANNEL) TYPE  /1BEA/RT_CRMB_DIS_CHANNEL
*"         OPTIONAL
*"     REFERENCE(IRT_BDI_DIVISION) TYPE  /1BEA/RT_CRMB_DIVISION
*"         OPTIONAL
*"     REFERENCE(IRT_BDI_DOC_CURRENCY) TYPE  BEART_DOC_CURRENCY
*"         OPTIONAL
*"     REFERENCE(IRT_BDI_EXCHANGE_DATE) TYPE  BEART_EXCHANGE_DATE
*"         OPTIONAL
*"     REFERENCE(IRT_BDI_EXCHANGE_RATE) TYPE  BEART_EXCHANGE_RATE
*"         OPTIONAL
*"     REFERENCE(IRT_BDI_GROSS_VALUE) TYPE  BEART_GROSS_VALUE
*"         OPTIONAL
*"     REFERENCE(IRT_BDI_IS_REVERSED) TYPE  BEART_IS_REVERSED
*"         OPTIONAL
*"     REFERENCE(IRT_BDI_ITEMNO_EXT) TYPE  BEART_ITEMNO_EXT OPTIONAL
*"     REFERENCE(IRT_BDI_ITEM_CATEGORY) TYPE  BEART_ITEM_CATEGORY
*"         OPTIONAL
*"     REFERENCE(IRT_BDI_ITEM_TYPE) TYPE  BEART_ITEM_TYPE OPTIONAL
*"     REFERENCE(IRT_BDI_LOGSYS) TYPE  /1BEA/RT_CRMB_LOGSYS OPTIONAL
*"     REFERENCE(IRT_BDI_NET_VALUE) TYPE  BEART_NET_VALUE OPTIONAL
*"     REFERENCE(IRT_BDI_OBJTYPE) TYPE  /1BEA/RT_CRMB_OBJTYPE
*"         OPTIONAL
*"     REFERENCE(IRT_BDI_PARENT_ITEMNO) TYPE
*"                             /1BEA/RT_CRMB_PARENT_ITEMNO OPTIONAL
*"     REFERENCE(IRT_BDI_PRODUCT) TYPE  /1BEA/RT_CRMB_PRODUCT
*"         OPTIONAL
*"     REFERENCE(IRT_BDI_PRODUCT_DESCR) TYPE
*"                             /1BEA/RT_CRMB_PRODUCT_DESCR OPTIONAL
*"     REFERENCE(IRT_BDI_REVERSAL) TYPE  BEART_REVERSAL OPTIONAL
*"     REFERENCE(IRT_BDI_SALES_ORG) TYPE  /1BEA/RT_CRMB_SALES_ORG
*"         OPTIONAL
*"     REFERENCE(IRT_BDI_SERVICE_ORG) TYPE  /1BEA/RT_CRMB_SERVICE_ORG
*"         OPTIONAL
*"     REFERENCE(IRT_BDI_SRC_GUID) TYPE  /1BEA/RT_CRMB_SRC_GUID
*"         OPTIONAL
*"     REFERENCE(IRT_BDI_SRC_HEADNO) TYPE  /1BEA/RT_CRMB_SRC_HEADNO
*"         OPTIONAL
*"     REFERENCE(IRT_BDI_SRC_ITEMNO) TYPE  /1BEA/RT_CRMB_SRC_ITEMNO
*"         OPTIONAL
*"     REFERENCE(IRT_BDI_SRC_ITEM_TYPE) TYPE
*"                             /1BEA/RT_CRMB_SRC_ITEM_TYPE OPTIONAL
*"     REFERENCE(IRT_BDI_SRC_PROCESS_TYPE) TYPE
*"                             /1BEA/RT_CRMB_SRC_PROCESS_TYPE
*"         OPTIONAL
*"     REFERENCE(IRT_BDI_SRVDOC_SOURCE) TYPE  BEART_SRVDOC_SOURCE
*"         OPTIONAL
*"     REFERENCE(IRT_BDI_TAX_VALUE) TYPE  BEART_TAX_VALUE OPTIONAL
*"     REFERENCE(IT_BDH_WHERE_CONDITION) TYPE
*"                             COMT_WHERE_CONDITION_TAB OPTIONAL
*"     REFERENCE(IT_BDI_WHERE_CONDITION) TYPE
*"                             COMT_WHERE_CONDITION_TAB OPTIONAL
*"     REFERENCE(IV_MAXROWS) TYPE  BAPIMAXROW
*"         DEFAULT                    0
*"  EXPORTING
*"     REFERENCE(ET_BDH) TYPE  /1BEA/T_CRMB_BDH_WRK
*"--------------------------------------------------------------------
*======================================================================
*
* The following coding has been generated. Please do not change
* manually. All modifications will be lost by new generation.
*
* The code generation was triggered by
*
* Name  : DDIC
* Date  : 03.05.2012
* Time  : 13:52:50
*
*======================================================================
* Selection of billing document headers according to header AND item
* attributes (= complete bill docs are identified)

*********************************************************************
* Declaration Part
*********************************************************************
  DATA:
    LV_WITHITEMS        TYPE BEA_BOOLEAN,
    LS_BDH_WRK          TYPE /1bea/s_CRMB_BDH_wrk,
    LRT_DUMMY           TYPE BEART_BDH_GUID,
    LT_AUTH_OBJ         TYPE XUOBJECT_T,
    LT_RANGE_APPL       TYPE CRMT_RANGE_APPL,
    LT_RANGE_BILL_ORG   TYPE CRMT_RANGE_BILL_ORG,
    LT_RANGE_BILL_TYPE  TYPE CRMT_RANGE_BILL_TYPE.

*********************************************************************
* Implementation Part
*********************************************************************
*====================================================================
* Prepare and Check
*====================================================================
  CLEAR ET_BDH.
  IF NOT ET_BDH IS REQUESTED.
    EXIT.
  ENDIF.
*====================================================================
* Is it necessary to search with item attributes, too?
*====================================================================
  IF       IT_BDI_WHERE_CONDITION IS NOT INITIAL OR
            NOT IRT_BDI_BDI_GUID IS INITIAL
           OR NOT IRT_BDI_BILL_RELEVANCE IS INITIAL
           OR NOT IRT_BDI_CREATION_CODE IS INITIAL
           OR NOT IRT_BDI_CREDIT_DEBIT IS INITIAL
           OR NOT IRT_BDI_DIS_CHANNEL IS INITIAL
           OR NOT IRT_BDI_DIVISION IS INITIAL
           OR NOT IRT_BDI_DOC_CURRENCY IS INITIAL
           OR NOT IRT_BDI_EXCHANGE_DATE IS INITIAL
           OR NOT IRT_BDI_EXCHANGE_RATE IS INITIAL
           OR NOT IRT_BDI_GROSS_VALUE IS INITIAL
           OR NOT IRT_BDI_IS_REVERSED IS INITIAL
           OR NOT IRT_BDI_ITEMNO_EXT IS INITIAL
           OR NOT IRT_BDI_ITEM_CATEGORY IS INITIAL
           OR NOT IRT_BDI_ITEM_TYPE IS INITIAL
           OR NOT IRT_BDI_LOGSYS IS INITIAL
           OR NOT IRT_BDI_NET_VALUE IS INITIAL
           OR NOT IRT_BDI_OBJTYPE IS INITIAL
           OR NOT IRT_BDI_PARENT_ITEMNO IS INITIAL
           OR NOT IRT_BDI_PRODUCT IS INITIAL
           OR NOT IRT_BDI_PRODUCT_DESCR IS INITIAL
           OR NOT IRT_BDI_REVERSAL IS INITIAL
           OR NOT IRT_BDI_SALES_ORG IS INITIAL
           OR NOT IRT_BDI_SERVICE_ORG IS INITIAL
           OR NOT IRT_BDI_SRC_GUID IS INITIAL
           OR NOT IRT_BDI_SRC_HEADNO IS INITIAL
           OR NOT IRT_BDI_SRC_ITEMNO IS INITIAL
           OR NOT IRT_BDI_SRC_ITEM_TYPE IS INITIAL
           OR NOT IRT_BDI_SRC_PROCESS_TYPE IS INITIAL
           OR NOT IRT_BDI_SRVDOC_SOURCE IS INITIAL
           OR NOT IRT_BDI_TAX_VALUE IS INITIAL
    .
    lv_withitems = gc_true.
  ENDIF.
    IF lv_withitems = gc_true.
*====================================================================
* SELECT also with item criteria
*====================================================================
      IF iv_auth_check EQ gc_true.
        APPEND 'BEA_BDH' TO lt_auth_obj.
        CALL FUNCTION 'BEA_AUTH_RANGES'
          EXPORTING
            it_auth_objects          = LT_AUTH_OBJ
            iv_activity              = GC_ACTV_DISPLAY
          IMPORTING
            ET_RANGE_APPL            = LT_RANGE_APPL
            ET_RANGE_BILL_ORG        = LT_RANGE_BILL_ORG
            ET_RANGE_BILL_TYPE       = LT_RANGE_BILL_TYPE
          EXCEPTIONS
            NO_AUTH                  = 1
            OTHERS                   = 2.
        CHECK sy-subrc = 0.
* Check whether user has rights for this application
        CHECK GC_APPL IN LT_RANGE_APPL.
        SELECT *
          FROM /1BEA/CRMB_BDH AS BDH
          INTO CORRESPONDING FIELDS OF LS_BDH_WRK
          WHERE BDH~BDH_GUID IN LRT_DUMMY AND
          (IT_BDH_WHERE_CONDITION)
          AND BDH~BILL_TYPE IN LT_RANGE_BILL_TYPE
          AND BDH~BILL_ORG IN LT_RANGE_BILL_ORG
          AND BDH~ARCHIVABLE IN IRT_BDH_ARCHIVABLE
          AND BDH~BDH_GUID IN IRT_BDH_BDH_GUID
          AND BDH~BILL_CATEGORY IN IRT_BDH_BILL_CATEGORY
          AND BDH~BILL_DATE IN IRT_BDH_BILL_DATE
          AND BDH~BILL_ORG IN IRT_BDH_BILL_ORG
          AND BDH~BILL_TYPE IN IRT_BDH_BILL_TYPE
          AND BDH~CANCEL_FLAG IN IRT_BDH_CANCEL_FLAG
          AND BDH~CRP_GUID IN IRT_BDH_CRP_GUID
          AND BDH~DOC_CURRENCY IN IRT_BDH_DOC_CURRENCY
          AND BDH~HEADNO_EXT IN IRT_BDH_HEADNO_EXT
          AND BDH~LOGSYS IN IRT_BDH_LOGSYS
          AND BDH~MAINT_DATE IN IRT_BDH_MAINT_DATE
          AND BDH~MAINT_TIME IN IRT_BDH_MAINT_TIME
          AND BDH~MAINT_USER IN IRT_BDH_MAINT_USER
          AND BDH~NET_VALUE IN IRT_BDH_NET_VALUE
          AND BDH~OBJTYPE IN IRT_BDH_OBJTYPE
          AND BDH~PAYER IN IRT_BDH_PAYER
          AND BDH~PRIC_PROC IN IRT_BDH_PRIC_PROC
          AND BDH~REFERENCE_NO IN IRT_BDH_REFERENCE_NO
          AND BDH~REF_CURRENCY IN IRT_BDH_REF_CURRENCY
          AND BDH~SPLIT_CRITERIA IN IRT_BDH_SPLIT_CRITERIA
          AND BDH~TAX_VALUE IN IRT_BDH_TAX_VALUE
          AND BDH~TERMS_OF_PAYMENT IN IRT_BDH_TERMS_OF_PAYMENT
          AND BDH~TRANSFER_DATE IN IRT_BDH_TRANSFER_DATE
          AND BDH~TRANSFER_ERROR IN IRT_BDH_TRANSFER_ERROR
          AND BDH~TRANSFER_STATUS IN IRT_BDH_TRANSFER_STATUS
          AND EXISTS (
             SELECT * FROM /1BEA/CRMB_BDI AS BDI
                WHERE BDI~bdh_guid = BDH~bdh_guid AND
                (IT_BDI_WHERE_CONDITION)
                AND BDI~BDI_GUID IN IRT_BDI_BDI_GUID
                AND BDI~BILL_RELEVANCE IN IRT_BDI_BILL_RELEVANCE
                AND BDI~CREATION_CODE IN IRT_BDI_CREATION_CODE
                AND BDI~CREDIT_DEBIT IN IRT_BDI_CREDIT_DEBIT
                AND BDI~DIS_CHANNEL IN IRT_BDI_DIS_CHANNEL
                AND BDI~DIVISION IN IRT_BDI_DIVISION
                AND BDI~DOC_CURRENCY IN IRT_BDI_DOC_CURRENCY
                AND BDI~EXCHANGE_DATE IN IRT_BDI_EXCHANGE_DATE
                AND BDI~EXCHANGE_RATE IN IRT_BDI_EXCHANGE_RATE
                AND BDI~GROSS_VALUE IN IRT_BDI_GROSS_VALUE
                AND BDI~IS_REVERSED IN IRT_BDI_IS_REVERSED
                AND BDI~ITEMNO_EXT IN IRT_BDI_ITEMNO_EXT
                AND BDI~ITEM_CATEGORY IN IRT_BDI_ITEM_CATEGORY
                AND BDI~ITEM_TYPE IN IRT_BDI_ITEM_TYPE
                AND BDI~LOGSYS IN IRT_BDI_LOGSYS
                AND BDI~NET_VALUE IN IRT_BDI_NET_VALUE
                AND BDI~OBJTYPE IN IRT_BDI_OBJTYPE
                AND BDI~PARENT_ITEMNO IN IRT_BDI_PARENT_ITEMNO
                AND BDI~PRODUCT IN IRT_BDI_PRODUCT
                AND BDI~PRODUCT_DESCR IN IRT_BDI_PRODUCT_DESCR
                AND BDI~REVERSAL IN IRT_BDI_REVERSAL
                AND BDI~SALES_ORG IN IRT_BDI_SALES_ORG
                AND BDI~SERVICE_ORG IN IRT_BDI_SERVICE_ORG
                AND BDI~SRC_GUID IN IRT_BDI_SRC_GUID
                AND BDI~SRC_HEADNO IN IRT_BDI_SRC_HEADNO
                AND BDI~SRC_ITEMNO IN IRT_BDI_SRC_ITEMNO
                AND BDI~SRC_ITEM_TYPE IN IRT_BDI_SRC_ITEM_TYPE
                AND BDI~SRC_PROCESS_TYPE IN IRT_BDI_SRC_PROCESS_TYPE
                AND BDI~SRVDOC_SOURCE IN IRT_BDI_SRVDOC_SOURCE
                AND BDI~TAX_VALUE IN IRT_BDI_TAX_VALUE
                ).
          INSERT ls_bdh_wrk INTO TABLE et_bdh.
          IF iv_maxrows IS NOT INITIAL.
            IF LINES( et_bdh ) GE iv_maxrows.
              EXIT. "the select
            ENDIF.
          ENDIF.
      ENDSELECT.
      ELSE.
        SELECT *
           FROM /1BEA/CRMB_BDH AS BDH
           INTO CORRESPONDING FIELDS OF TABLE ET_BDH
           UP TO IV_MAXROWS ROWS
           WHERE BDH~BDH_GUID IN LRT_DUMMY AND
           (IT_BDH_WHERE_CONDITION)
           AND BDH~ARCHIVABLE IN IRT_BDH_ARCHIVABLE
           AND BDH~BDH_GUID IN IRT_BDH_BDH_GUID
           AND BDH~BILL_CATEGORY IN IRT_BDH_BILL_CATEGORY
           AND BDH~BILL_DATE IN IRT_BDH_BILL_DATE
           AND BDH~BILL_ORG IN IRT_BDH_BILL_ORG
           AND BDH~BILL_TYPE IN IRT_BDH_BILL_TYPE
           AND BDH~CANCEL_FLAG IN IRT_BDH_CANCEL_FLAG
           AND BDH~CRP_GUID IN IRT_BDH_CRP_GUID
           AND BDH~DOC_CURRENCY IN IRT_BDH_DOC_CURRENCY
           AND BDH~HEADNO_EXT IN IRT_BDH_HEADNO_EXT
           AND BDH~LOGSYS IN IRT_BDH_LOGSYS
           AND BDH~MAINT_DATE IN IRT_BDH_MAINT_DATE
           AND BDH~MAINT_TIME IN IRT_BDH_MAINT_TIME
           AND BDH~MAINT_USER IN IRT_BDH_MAINT_USER
           AND BDH~NET_VALUE IN IRT_BDH_NET_VALUE
           AND BDH~OBJTYPE IN IRT_BDH_OBJTYPE
           AND BDH~PAYER IN IRT_BDH_PAYER
           AND BDH~PRIC_PROC IN IRT_BDH_PRIC_PROC
           AND BDH~REFERENCE_NO IN IRT_BDH_REFERENCE_NO
           AND BDH~REF_CURRENCY IN IRT_BDH_REF_CURRENCY
           AND BDH~SPLIT_CRITERIA IN IRT_BDH_SPLIT_CRITERIA
           AND BDH~TAX_VALUE IN IRT_BDH_TAX_VALUE
           AND BDH~TERMS_OF_PAYMENT IN IRT_BDH_TERMS_OF_PAYMENT
           AND BDH~TRANSFER_DATE IN IRT_BDH_TRANSFER_DATE
           AND BDH~TRANSFER_ERROR IN IRT_BDH_TRANSFER_ERROR
           AND BDH~TRANSFER_STATUS IN IRT_BDH_TRANSFER_STATUS
           AND EXISTS (
            SELECT * FROM /1BEA/CRMB_BDI AS BDI
              WHERE BDI~bdh_guid = BDH~bdh_guid AND
              (IT_BDI_WHERE_CONDITION)
              AND BDI~BDI_GUID IN IRT_BDI_BDI_GUID
              AND BDI~BILL_RELEVANCE IN IRT_BDI_BILL_RELEVANCE
              AND BDI~CREATION_CODE IN IRT_BDI_CREATION_CODE
              AND BDI~CREDIT_DEBIT IN IRT_BDI_CREDIT_DEBIT
              AND BDI~DIS_CHANNEL IN IRT_BDI_DIS_CHANNEL
              AND BDI~DIVISION IN IRT_BDI_DIVISION
              AND BDI~DOC_CURRENCY IN IRT_BDI_DOC_CURRENCY
              AND BDI~EXCHANGE_DATE IN IRT_BDI_EXCHANGE_DATE
              AND BDI~EXCHANGE_RATE IN IRT_BDI_EXCHANGE_RATE
              AND BDI~GROSS_VALUE IN IRT_BDI_GROSS_VALUE
              AND BDI~IS_REVERSED IN IRT_BDI_IS_REVERSED
              AND BDI~ITEMNO_EXT IN IRT_BDI_ITEMNO_EXT
              AND BDI~ITEM_CATEGORY IN IRT_BDI_ITEM_CATEGORY
              AND BDI~ITEM_TYPE IN IRT_BDI_ITEM_TYPE
              AND BDI~LOGSYS IN IRT_BDI_LOGSYS
              AND BDI~NET_VALUE IN IRT_BDI_NET_VALUE
              AND BDI~OBJTYPE IN IRT_BDI_OBJTYPE
              AND BDI~PARENT_ITEMNO IN IRT_BDI_PARENT_ITEMNO
              AND BDI~PRODUCT IN IRT_BDI_PRODUCT
              AND BDI~PRODUCT_DESCR IN IRT_BDI_PRODUCT_DESCR
              AND BDI~REVERSAL IN IRT_BDI_REVERSAL
              AND BDI~SALES_ORG IN IRT_BDI_SALES_ORG
              AND BDI~SERVICE_ORG IN IRT_BDI_SERVICE_ORG
              AND BDI~SRC_GUID IN IRT_BDI_SRC_GUID
              AND BDI~SRC_HEADNO IN IRT_BDI_SRC_HEADNO
              AND BDI~SRC_ITEMNO IN IRT_BDI_SRC_ITEMNO
              AND BDI~SRC_ITEM_TYPE IN IRT_BDI_SRC_ITEM_TYPE
              AND BDI~SRC_PROCESS_TYPE IN IRT_BDI_SRC_PROCESS_TYPE
              AND BDI~SRVDOC_SOURCE IN IRT_BDI_SRVDOC_SOURCE
              AND BDI~TAX_VALUE IN IRT_BDI_TAX_VALUE
              ).
      ENDIF.
    ELSE.
*====================================================================
* SELECT with header criteria only
*====================================================================
      IF iv_auth_check EQ gc_true.
        APPEND 'BEA_BDH' TO lt_auth_obj.
        CALL FUNCTION 'BEA_AUTH_RANGES'
          EXPORTING
            it_auth_objects          = LT_AUTH_OBJ
            iv_activity              = GC_ACTV_DISPLAY
          IMPORTING
            ET_RANGE_APPL            = LT_RANGE_APPL
            ET_RANGE_BILL_ORG        = LT_RANGE_BILL_ORG
            ET_RANGE_BILL_TYPE       = LT_RANGE_BILL_TYPE
          EXCEPTIONS
            NO_AUTH                  = 1
            OTHERS                   = 2.
        CHECK sy-subrc = 0.
* Check whether user has rights for this application
        CHECK GC_APPL IN LT_RANGE_APPL.
        SELECT * FROM /1BEA/CRMB_BDH
          INTO CORRESPONDING FIELDS OF LS_BDH_WRK
          WHERE
           (IT_BDH_WHERE_CONDITION)
           AND BILL_TYPE IN LT_RANGE_BILL_TYPE
           AND BILL_ORG IN LT_RANGE_BILL_ORG AND
            ARCHIVABLE IN IRT_BDH_ARCHIVABLE
           AND BDH_GUID IN IRT_BDH_BDH_GUID
           AND BILL_CATEGORY IN IRT_BDH_BILL_CATEGORY
           AND BILL_DATE IN IRT_BDH_BILL_DATE
           AND BILL_ORG IN IRT_BDH_BILL_ORG
           AND BILL_TYPE IN IRT_BDH_BILL_TYPE
           AND CANCEL_FLAG IN IRT_BDH_CANCEL_FLAG
           AND CRP_GUID IN IRT_BDH_CRP_GUID
           AND DOC_CURRENCY IN IRT_BDH_DOC_CURRENCY
           AND HEADNO_EXT IN IRT_BDH_HEADNO_EXT
           AND LOGSYS IN IRT_BDH_LOGSYS
           AND MAINT_DATE IN IRT_BDH_MAINT_DATE
           AND MAINT_TIME IN IRT_BDH_MAINT_TIME
           AND MAINT_USER IN IRT_BDH_MAINT_USER
           AND NET_VALUE IN IRT_BDH_NET_VALUE
           AND OBJTYPE IN IRT_BDH_OBJTYPE
           AND PAYER IN IRT_BDH_PAYER
           AND PRIC_PROC IN IRT_BDH_PRIC_PROC
           AND REFERENCE_NO IN IRT_BDH_REFERENCE_NO
           AND REF_CURRENCY IN IRT_BDH_REF_CURRENCY
           AND SPLIT_CRITERIA IN IRT_BDH_SPLIT_CRITERIA
           AND TAX_VALUE IN IRT_BDH_TAX_VALUE
           AND TERMS_OF_PAYMENT IN IRT_BDH_TERMS_OF_PAYMENT
           AND TRANSFER_DATE IN IRT_BDH_TRANSFER_DATE
           AND TRANSFER_ERROR IN IRT_BDH_TRANSFER_ERROR
           AND TRANSFER_STATUS IN IRT_BDH_TRANSFER_STATUS.
           INSERT ls_bdh_wrk INTO TABLE et_bdh.
           IF iv_maxrows IS NOT INITIAL.
              IF LINES( et_bdh ) GE iv_maxrows.
                EXIT. "the select
              ENDIF.
            ENDIF.
        ENDSELECT.
      ELSE.
        SELECT * FROM /1BEA/CRMB_BDH
          INTO CORRESPONDING FIELDS OF TABLE ET_BDH
          UP TO IV_MAXROWS ROWS
          WHERE
           (IT_BDH_WHERE_CONDITION) AND
            ARCHIVABLE IN IRT_BDH_ARCHIVABLE
           AND BDH_GUID IN IRT_BDH_BDH_GUID
           AND BILL_CATEGORY IN IRT_BDH_BILL_CATEGORY
           AND BILL_DATE IN IRT_BDH_BILL_DATE
           AND BILL_ORG IN IRT_BDH_BILL_ORG
           AND BILL_TYPE IN IRT_BDH_BILL_TYPE
           AND CANCEL_FLAG IN IRT_BDH_CANCEL_FLAG
           AND CRP_GUID IN IRT_BDH_CRP_GUID
           AND DOC_CURRENCY IN IRT_BDH_DOC_CURRENCY
           AND HEADNO_EXT IN IRT_BDH_HEADNO_EXT
           AND LOGSYS IN IRT_BDH_LOGSYS
           AND MAINT_DATE IN IRT_BDH_MAINT_DATE
           AND MAINT_TIME IN IRT_BDH_MAINT_TIME
           AND MAINT_USER IN IRT_BDH_MAINT_USER
           AND NET_VALUE IN IRT_BDH_NET_VALUE
           AND OBJTYPE IN IRT_BDH_OBJTYPE
           AND PAYER IN IRT_BDH_PAYER
           AND PRIC_PROC IN IRT_BDH_PRIC_PROC
           AND REFERENCE_NO IN IRT_BDH_REFERENCE_NO
           AND REF_CURRENCY IN IRT_BDH_REF_CURRENCY
           AND SPLIT_CRITERIA IN IRT_BDH_SPLIT_CRITERIA
           AND TAX_VALUE IN IRT_BDH_TAX_VALUE
           AND TERMS_OF_PAYMENT IN IRT_BDH_TERMS_OF_PAYMENT
           AND TRANSFER_DATE IN IRT_BDH_TRANSFER_DATE
           AND TRANSFER_ERROR IN IRT_BDH_TRANSFER_ERROR
           AND TRANSFER_STATUS IN IRT_BDH_TRANSFER_STATUS.
      ENDIF.
    ENDIF.
ENDFUNCTION.
