*****************************************************************
*   THIS FILE IS GENERATED BY THE FUNCTION LIBRARY.             *
*   NEVER CHANGE IT MANUALLY, PLEASE!                           *
*****************************************************************
INCLUDE %2f1BEA%2fLCRMB_DL_CRT_OU01.
                    "/1BEA/CRMB_DL_CRT_O_DOC_SET
