*****************************************************************
*   THIS FILE IS GENERATED BY THE FUNCTION LIBRARY.             *
*   NEVER CHANGE IT MANUALLY, PLEASE!                           *
*****************************************************************
INCLUDE %2f1BEA%2fLCRMB_DL_PAR_OU01.
                    "/1BEA/CRMB_DL_PAR_O_COMPRESS
INCLUDE %2f1BEA%2fLCRMB_DL_PAR_OU02.
                    "/1BEA/CRMB_DL_PAR_O_COPY
INCLUDE %2f1BEA%2fLCRMB_DL_PAR_OU03.
                    "/1BEA/CRMB_DL_PAR_O_CREATE
INCLUDE %2f1BEA%2fLCRMB_DL_PAR_OU04.
                    "/1BEA/CRMB_DL_PAR_O_DELETE
INCLUDE %2f1BEA%2fLCRMB_DL_PAR_OU05.
                    "/1BEA/CRMB_DL_PAR_O_DERIVE
INCLUDE %2f1BEA%2fLCRMB_DL_PAR_OU06.
                    "/1BEA/CRMB_DL_PAR_O_DETERMINE
INCLUDE %2f1BEA%2fLCRMB_DL_PAR_OU07.
                    "/1BEA/CRMB_DL_PAR_O_GET_CTRL
INCLUDE %2f1BEA%2fLCRMB_DL_PAR_OU08.
                    "/1BEA/CRMB_DL_PAR_O_REFRESH
INCLUDE %2f1BEA%2fLCRMB_DL_PAR_OU09.
                    "/1BEA/CRMB_DL_PAR_O_SAVE
