*======================================================================
*
* The following coding has been generated. Please do not change
* manually. All modifications will be lost by new generation.
*
* The code generation was triggered by
*
* Name  : DDIC
* Date  : 03.05.2012
* Time  : 13:53:10
*
*======================================================================
DATA:
  LRS_DG_LOGSYS TYPE /1BEA/RS_CRMB_DG_LOGSYS,  "#EC NEEDED
  LRT_DG_LOGSYS TYPE /1BEA/RT_CRMB_DG_LOGSYS,  "#EC NEEDED
  LRS_DG_OBJTYPE TYPE /1BEA/RS_CRMB_DG_OBJTYPE,  "#EC NEEDED
  LRT_DG_OBJTYPE TYPE /1BEA/RT_CRMB_DG_OBJTYPE,  "#EC NEEDED
  LRS_DG_SRC_HEADNO TYPE /1BEA/RS_CRMB_DG_SRC_HEADNO,  "#EC NEEDED
  LRT_DG_SRC_HEADNO TYPE /1BEA/RT_CRMB_DG_SRC_HEADNO,  "#EC NEEDED
  LRS_DG_SRC_ITEMNO TYPE /1BEA/RS_CRMB_DG_SRC_ITEMNO,  "#EC NEEDED
  LRT_DG_SRC_ITEMNO TYPE /1BEA/RT_CRMB_DG_SRC_ITEMNO,  "#EC NEEDED
  LT_BDI_WRK     TYPE /1BEA/T_CRMB_BDI_WRK,
  LT_BDH_WRK     TYPE /1BEA/T_CRMB_BDH_WRK,
  LS_BDI_WRK     TYPE /1BEA/S_CRMB_BDI_WRK.

* Translate external reference to internal GUID(s)
* (bill doc has to exist on database)
CASE IS_DLI-DG_OBJTYPE.
WHEN GC_BOR_BDI.
  LRS_DG_LOGSYS-SIGN    = GC_INCLUDE.
  LRS_DG_LOGSYS-OPTION  = GC_EQUAL.
  LRS_DG_LOGSYS-LOW     = IS_DLI-DG_LOGSYS.
  APPEND LRS_DG_LOGSYS TO LRT_DG_LOGSYS.
  LRS_DG_OBJTYPE-SIGN    = GC_INCLUDE.
  LRS_DG_OBJTYPE-OPTION  = GC_EQUAL.
  LRS_DG_OBJTYPE-LOW     = IS_DLI-DG_OBJTYPE.
  APPEND LRS_DG_OBJTYPE TO LRT_DG_OBJTYPE.
  LRS_DG_SRC_HEADNO-SIGN    = GC_INCLUDE.
  LRS_DG_SRC_HEADNO-OPTION  = GC_EQUAL.
  LRS_DG_SRC_HEADNO-LOW     = IS_DLI-DG_SRC_HEADNO.
  APPEND LRS_DG_SRC_HEADNO TO LRT_DG_SRC_HEADNO.
  LRS_DG_SRC_ITEMNO-SIGN    = GC_INCLUDE.
  LRS_DG_SRC_ITEMNO-OPTION  = GC_EQUAL.
  LRS_DG_SRC_ITEMNO-LOW     = IS_DLI-DG_SRC_ITEMNO.
  APPEND LRS_DG_SRC_ITEMNO TO LRT_DG_SRC_ITEMNO.
  CALL FUNCTION '/1BEA/CRMB_BD_O_GETLIST'
    EXPORTING
      IV_COMPLIT         = SPACE
      IRT_BDH_LOGSYS     = LRT_DG_LOGSYS
      IRT_BDH_HEADNO_EXT = LRT_DG_SRC_HEADNO
      IRT_BDI_ITEMNO_EXT = LRT_DG_SRC_ITEMNO
    IMPORTING
      ET_BDH             = LT_BDH_WRK
      ET_BDI             = LT_BDI_WRK.
  IF LT_BDH_WRK IS INITIAL OR LT_BDI_WRK IS INITIAL.
    MESSAGE E654(BEA) WITH IS_DLI-SRC_HEADNO IS_DLI-SRC_ITEMNO
                      INTO GV_DUMMY.
    CALL FUNCTION '/1BEA/CRMB_DL_O_MESSAGE_ADD'
      EXPORTING
        IV_OBJECT      = 'DL'
        IV_CONTAINER   = 'DLI'
        IS_DLI_WRK     = IS_DLI
      IMPORTING
        ET_RETURN      = ET_RETURN.
    RETURN.
  ENDIF.
  READ TABLE LT_BDI_WRK INTO LS_BDI_WRK INDEX 1.

   CALL FUNCTION '/1BEA/CRMB_BD_O_CHECK_CORRABL'
     EXPORTING
       IS_DLI            = IS_DLI
       IS_BDI            = LS_BDI_WRK
     EXCEPTIONS
       NOT_ALLOWED       = 1
       OTHERS            = 2.
   IF sy-subrc <> 0.
     MESSAGE ID SY-MSGID TYPE SY-MSGTY NUMBER SY-MSGNO
             WITH SY-MSGV1 SY-MSGV2 SY-MSGV3 SY-MSGV4 INTO GV_DUMMY.
     CALL FUNCTION '/1BEA/CRMB_DL_O_MESSAGE_ADD'
       EXPORTING
         IV_OBJECT      = 'DL'
         IV_CONTAINER   = 'DLI'
         IS_DLI_WRK     = IS_DLI
       IMPORTING
         ET_RETURN      = ET_RETURN.
     RETURN.
   ENDIF.

*  CALL FUNCTION '/1BEA/CRMB_BD_O_ADD_TO_BUFFER'
*    EXPORTING
*      IT_BDI        = LT_BDI_WRK.  " does not support initial UPD_TYPE!!!
  LS_DLI_WRK-BDI_GUID = LS_BDI_WRK-BDI_GUID.
  APPEND LS_DLI_WRK TO LT_DLI.

ENDCASE.
