FUNCTION /1BEA/CRMB_BD_PRC_O_HD_MAPIN.
*"--------------------------------------------------------------------
*"*"Local Interface:
*"  IMPORTING
*"     REFERENCE(IS_BDH_WRK) TYPE  /1BEA/S_CRMB_BDH_WRK
*"  EXPORTING
*"     REFERENCE(ES_PRC_HEAD) TYPE  PRCT_HEAD_COM
*"     REFERENCE(ES_PRC_H_ACS) TYPE  CRMT_ACS_H_HEADER_ONLY
*"     REFERENCE(ET_RETURN) TYPE  BEAT_RETURN
*"  EXCEPTIONS
*"      REJECT
*"--------------------------------------------------------------------
*======================================================================
*
* The following coding has been generated. Please do not change
* manually. All modifications will be lost by new generation.
*
* The code generation was triggered by
*
* Name  : DDIC
* Date  : 03.05.2012
* Time  : 13:53:02
*
*======================================================================
  CONSTANTS:
    LC_APPLICATION TYPE /SAPCND/APPLICATION VALUE 'CRM',
    LC_USAGE       TYPE /SAPCND/USAGE       VALUE 'PR',
    LC_EXIT_NAME   TYPE EXIT_DEF            VALUE '/1BEA/CRMB_BD_PRC',
    LC_BOR_HEAD    TYPE PRCT_ATTR_NAME      VALUE 'BOR_OBJTYP_HDR'.
  DATA:
    LS_PRC_HEAD        TYPE PRCT_HEAD_COM,
    LT_RETURN          TYPE BEAT_RETURN,
    LS_ATTR_NAME_VALUE TYPE PRCT_ATTR_NAME_VALUE.

* Fill fix Header Fields
  MOVE IS_BDH_WRK-BILL_DATE TO LS_PRC_HEAD-PRSDT.
  MOVE IS_BDH_WRK-PRIC_PROC TO LS_PRC_HEAD-KALSM.
  MOVE IS_BDH_WRK-DOC_CURRENCY TO LS_PRC_HEAD-WAERK.
  MOVE IS_BDH_WRK-REF_CURRENCY TO LS_PRC_HEAD-HWAER.
  MOVE IS_BDH_WRK-EXCHANGE_TYPE TO LS_PRC_HEAD-KURST.
* Determine the relevant attributes
  CALL FUNCTION '/1BEA/CRMB_BD_PRC_O_GET_INFO'
    EXPORTING
      IV_APPLICATION           = LC_APPLICATION
      IV_USAGE                 = LC_USAGE
      IV_PRIC_PROC             = IS_BDH_WRK-PRIC_PROC
    EXCEPTIONS
      WRONG_CALL               = 1
      IPC_ERROR                = 2
      SESSION_BEGIN            = 3
      OTHERS                   = 4.
    IF SY-SUBRC NE 0.
      MESSAGE ID SY-MSGID TYPE SY-MSGTY NUMBER SY-MSGNO
              WITH SY-MSGV1 SY-MSGV2 SY-MSGV3 SY-MSGV4 INTO GV_DUMMY.
      PERFORM MSG_ADD USING SPACE SPACE SPACE SPACE CHANGING ET_RETURN.
      MESSAGE ID SY-MSGID TYPE SY-MSGTY NUMBER SY-MSGNO
              WITH SY-MSGV1 SY-MSGV2 SY-MSGV3 SY-MSGV4
              RAISING REJECT.
    ENDIF.

  READ TABLE GT_ALL_ATTR_NAMES TRANSPORTING NO FIELDS
    WITH KEY TABLE_LINE = LC_BOR_HEAD
    BINARY SEARCH.
  IF SY-SUBRC EQ 0.
    LS_ATTR_NAME_VALUE-ATTR_NAME = LC_BOR_HEAD.
    LS_ATTR_NAME_VALUE-ATTR_VALUE = GC_BOR_BDH.
    PERFORM FILL_HEAD_NAME_VALUE_TAB USING LS_ATTR_NAME_VALUE
                                           GC_TRUE
                                     CHANGING LS_PRC_HEAD.
  ENDIF.

  LS_PRC_HEAD-KAPPL = LC_APPLICATION.


  IF NOT GV_MAPPING_EXIT IS INITIAL.
    CLEAR LT_RETURN.
    CALL BADI GV_MAPPING_EXIT->IN_MAP_HEAD
      EXPORTING  IS_BDH             = IS_BDH_WRK
                 IT_HEAD_ATTR_NAMES = GT_HEAD_ATTR_NAMES
      IMPORTING  ET_RETURN          = LT_RETURN
      CHANGING   CS_PRC_HEAD        = LS_PRC_HEAD
      EXCEPTIONS REJECT       = 1.
    IF SY-SUBRC NE 0.
      APPEND LINES OF LT_RETURN TO ET_RETURN.
      MESSAGE E200(BEA_PRC) RAISING REJECT.
    ENDIF.
  ENDIF.

  IF LS_PRC_HEAD-PRSDT IS INITIAL.
    LS_PRC_HEAD-PRSDT = SY-DATLO.
  ENDIF.

  ES_PRC_HEAD  = LS_PRC_HEAD.

ENDFUNCTION.

* Help Form Routines to fill the Name/Value Pair tables.
FORM FILL_HEAD_NAME_VALUE_TAB
  USING
    US_NAME_VALUE      TYPE PRCT_ATTR_NAME_VALUE
    UV_DELETE_EXISTING TYPE BEA_BOOLEAN
  CHANGING
    CS_PRC_HEAD        TYPE PRCT_HEAD_COM.

  CHECK US_NAME_VALUE-ATTR_NAME  IS NOT INITIAL AND
        US_NAME_VALUE-ATTR_VALUE IS NOT INITIAL.

  READ TABLE GT_HEAD_ATTR_NAMES
    TRANSPORTING NO FIELDS
    WITH KEY TABLE_LINE = US_NAME_VALUE-ATTR_NAME
    BINARY SEARCH.
  IF SY-SUBRC EQ 0.
    IF UV_DELETE_EXISTING EQ GC_TRUE.
      DELETE CS_PRC_HEAD-ATTR_NAME_VALUE
        WHERE ATTR_NAME EQ US_NAME_VALUE-ATTR_NAME.
    ENDIF.
    INSERT US_NAME_VALUE INTO TABLE CS_PRC_HEAD-ATTR_NAME_VALUE.
  ENDIF.
ENDFORM.
