*****************************************************************
*   THIS FILE IS GENERATED BY THE FUNCTION LIBRARY.             *
*   NEVER CHANGE IT MANUALLY, PLEASE!                           *
*****************************************************************
INCLUDE %2f1BEA%2fLCRMB_DL_ICX_OU01.
                    "/1BEA/CRMB_DL_ICX_O_DERIVE
INCLUDE %2f1BEA%2fLCRMB_DL_ICX_OU02.
                    "/1BEA/CRMB_DL_ICX_O_REFRESH
