*****************************************************************
*   THIS FILE IS GENERATED BY THE FUNCTION LIBRARY.             *
*   NEVER CHANGE IT MANUALLY, PLEASE!                           *
*****************************************************************
INCLUDE %2f1BEA%2fLCRMB_DL_UU01.
                    "/1BEA/CRMB_DL_U_CAPTION_DLI
INCLUDE %2f1BEA%2fLCRMB_DL_UU02.
                    "/1BEA/CRMB_DL_U_DETAIL_DLI
INCLUDE %2f1BEA%2fLCRMB_DL_UU03.
                    "/1BEA/CRMB_DL_U_DISPLAY
INCLUDE %2f1BEA%2fLCRMB_DL_UU04.
                    "/1BEA/CRMB_DL_U_INT2EXT
INCLUDE %2f1BEA%2fLCRMB_DL_UU05.
                    "/1BEA/CRMB_DL_U_OVERVIEW_DLI
INCLUDE %2f1BEA%2fLCRMB_DL_UU06.
                    "/1BEA/CRMB_DL_U_SHOW
INCLUDE %2f1BEA%2fLCRMB_DL_UU07.
                    "/1BEA/CRMB_DL_U_SHOWDETAIL
INCLUDE %2f1BEA%2fLCRMB_DL_UU08.
                    "/1BEA/CRMB_DL_U_SHOWLIST
INCLUDE %2f1BEA%2fLCRMB_DL_UU09.
                    "/1BEA/CRMB_DL_U_SHOW_ADD_DATA
