*======================================================================
*
* The following coding has been generated. Please do not change
* manually. All modifications will be lost by new generation.
*
* The code generation was triggered by
*
* Name  : DDIC
* Date  : 03.05.2012
* Time  : 13:53:10
*
*======================================================================
*--------------------------------------------------------------------*
*     FORM DRVODL_ELZ_REPLACE_INT_BY_EXT
*--------------------------------------------------------------------*
FORM DRVODL_ELZ_REPLACE_INT_BY_EXT
  CHANGING
    CS_DLI_WRK         TYPE /1BEA/S_CRMB_DLI_WRK.
  DATA:
    lV_NET_WEIGHT      TYPE CRMT_NET_WEIGHT,
    lV_GROSS_WEIGHT    TYPE CRMT_GROSS_WEIGHT,
    LV_UNIT            TYPE COMT_UNIT,
    LV_BILLED_QUANTITY TYPE COMT_QUANTITY,
    LT_RETURN          TYPE BEAT_RETURN,
    LV_RETURNCODE      TYPE SYSUBRC,
    LRS_DERIV_CATEGORY    TYPE /1BEA/RS_CRMB_DERIV_CATEGORY,
    LRT_DERIV_CATEGORY    TYPE /1BEA/RT_CRMB_DERIV_CATEGORY,
    LRS_LOGSYS    TYPE /1BEA/RS_CRMB_LOGSYS,
    LRT_LOGSYS    TYPE /1BEA/RT_CRMB_LOGSYS,
    LRS_OBJTYPE    TYPE /1BEA/RS_CRMB_OBJTYPE,
    LRT_OBJTYPE    TYPE /1BEA/RT_CRMB_OBJTYPE,
    LRS_SRC_HEADNO    TYPE /1BEA/RS_CRMB_SRC_HEADNO,
    LRT_SRC_HEADNO    TYPE /1BEA/RT_CRMB_SRC_HEADNO,
    LRS_SRC_ITEMNO    TYPE /1BEA/RS_CRMB_SRC_ITEMNO,
    LRT_SRC_ITEMNO    TYPE /1BEA/RT_CRMB_SRC_ITEMNO,
    LS_DLI_WRK        TYPE /1BEA/S_CRMB_DLI_WRK,
    LT_DLI_WRK        TYPE /1BEA/T_CRMB_DLI_WRK,
    LT_DLI_EXT        TYPE /1BEA/T_CRMB_DLI_WRK,
    LT_DLI_OV         TYPE /1BEA/T_CRMB_DLI_WRK.

  LS_DLI_WRK = CS_DLI_WRK.
  LS_DLI_WRK-DERIV_CATEGORY = GC_DERIV_ORIGIN.
  LRS_DERIV_CATEGORY-SIGN   = GC_INCLUDE.
  LRS_DERIV_CATEGORY-OPTION = GC_EQUAL.
  LRS_DERIV_CATEGORY-LOW    = LS_DLI_WRK-DERIV_CATEGORY.
  APPEND LRS_DERIV_CATEGORY TO LRT_DERIV_CATEGORY.
  LRS_LOGSYS-SIGN   = GC_INCLUDE.
  LRS_LOGSYS-OPTION = GC_EQUAL.
  LRS_LOGSYS-LOW    = LS_DLI_WRK-LOGSYS.
  APPEND LRS_LOGSYS TO LRT_LOGSYS.
  LRS_OBJTYPE-SIGN   = GC_INCLUDE.
  LRS_OBJTYPE-OPTION = GC_EQUAL.
  LRS_OBJTYPE-LOW    = LS_DLI_WRK-OBJTYPE.
  APPEND LRS_OBJTYPE TO LRT_OBJTYPE.
  LRS_SRC_HEADNO-SIGN   = GC_INCLUDE.
  LRS_SRC_HEADNO-OPTION = GC_EQUAL.
  LRS_SRC_HEADNO-LOW    = LS_DLI_WRK-SRC_HEADNO.
  APPEND LRS_SRC_HEADNO TO LRT_SRC_HEADNO.
  LRS_SRC_ITEMNO-SIGN   = GC_INCLUDE.
  LRS_SRC_ITEMNO-OPTION = GC_EQUAL.
  LRS_SRC_ITEMNO-LOW    = LS_DLI_WRK-SRC_ITEMNO.
  APPEND LRS_SRC_ITEMNO TO LRT_SRC_ITEMNO.
  CALL FUNCTION '/1BEA/CRMB_DL_O_GETLIST'
    EXPORTING
      IV_SORTREL        = GC_SORT_BY_EXTERNAL_REF
      IRT_DERIV_CATEGORY    = LRT_DERIV_CATEGORY
      IRT_LOGSYS    = LRT_LOGSYS
      IRT_OBJTYPE    = LRT_OBJTYPE
      IRT_SRC_HEADNO    = LRT_SRC_HEADNO
      IRT_SRC_ITEMNO    = LRT_SRC_ITEMNO
    IMPORTING
      ET_DLI            = LT_DLI_EXT.
  IF NOT LT_DLI_EXT IS INITIAL.
    CALL FUNCTION '/1BEA/CRMB_DL_O_GET_CHANGEABL'
       EXPORTING
         IT_DLI               = LT_DLI_EXT
       IMPORTING
         ET_DLI_WRK           = LT_DLI_WRK
         ET_DLI_OV            = LT_DLI_OV.
    IF NOT LT_DLI_OV IS INITIAL.
      SORT LT_DLI_OV BY INCOMP_ID DESCENDING.
      READ TABLE LT_DLI_OV INDEX 1 INTO LS_DLI_WRK.
    ELSEIF NOT LT_DLI_WRK IS INITIAL.
      READ TABLE LT_DLI_WRK INDEX 1 INTO LS_DLI_WRK.
      LS_DLI_WRK-BILL_STATUS = GC_BILLSTAT_TODO.
      CLEAR: LS_DLI_WRK-incomp_id,
             LS_DLI_WRK-BDI_GUID.
      CLEAR LS_DLI_WRK-quantity.
      CLEAR CS_DLI_WRK-net_weight.
      CLEAR CS_DLI_WRK-gross_weight.
    ENDIF.
  ENDIF.
  IF NOT LS_DLI_WRK IS INITIAL.
    IF LS_DLI_WRK-INCOMP_ID <> GC_INCOMP_ENQ.
      LV_UNIT = CS_DLI_WRK-QTY_UNIT.
      PERFORM PRDODL_QAZ_QUANTITY_GET
        USING
          LT_DLI_WRK
          LV_UNIT
        CHANGING
          LV_BILLED_QUANTITY
          LV_NET_WEIGHT
          LV_GROSS_WEIGHT
          LT_RETURN
          LV_RETURNCODE.
      IF LV_RETURNCODE IS INITIAL.
        ADD: LV_BILLED_QUANTITY TO LS_DLI_WRK-QUANTITY.
        ADD: LV_NET_WEIGHT TO LS_DLI_WRK-NET_WEIGHT,
             LV_GROSS_WEIGHT TO LS_DLI_WRK-GROSS_WEIGHT.
      ENDIF.
    ENDIF.
    CS_DLI_WRK = LS_DLI_WRK.
  ENDIF.
ENDFORM.            "REPLACE_INT_BY_EXT
