*****************************************************************
*   THIS FILE IS GENERATED BY THE FUNCTION LIBRARY.             *
*   NEVER CHANGE IT MANUALLY, PLEASE!                           *
*****************************************************************
INCLUDE %2f1BEA%2fLCRMB_BD_PPF_OU01.
                    "/1BEA/CRMB_BD_PPF_O_CONTEXTGET
INCLUDE %2f1BEA%2fLCRMB_BD_PPF_OU02.
                    "/1BEA/CRMB_BD_PPF_O_DETERMINE
INCLUDE %2f1BEA%2fLCRMB_BD_PPF_OU03.
                    "/1BEA/CRMB_BD_PPF_O_GETDATA
INCLUDE %2f1BEA%2fLCRMB_BD_PPF_OU04.
                    "/1BEA/CRMB_BD_PPF_O_PREPARE
INCLUDE %2f1BEA%2fLCRMB_BD_PPF_OU05.
                    "/1BEA/CRMB_BD_PPF_O_PREVIEW
INCLUDE %2f1BEA%2fLCRMB_BD_PPF_OU06.
                    "/1BEA/CRMB_BD_PPF_O_PRINT
INCLUDE %2f1BEA%2fLCRMB_BD_PPF_OU07.
                    "/1BEA/CRMB_BD_PPF_O_PROCS_DET
INCLUDE %2f1BEA%2fLCRMB_BD_PPF_OU08.
                    "/1BEA/CRMB_BD_PPF_O_REFRESH
INCLUDE %2f1BEA%2fLCRMB_BD_PPF_OU09.
                    "/1BEA/CRMB_BD_PPF_O_RENAME
INCLUDE %2f1BEA%2fLCRMB_BD_PPF_OU10.
                    "/1BEA/CRMB_BD_PPF_O_XIF_SEND
