*****************************************************************
*   THIS FILE IS GENERATED BY THE FUNCTION LIBRARY.             *
*   NEVER CHANGE IT MANUALLY, PLEASE!                           *
*****************************************************************
INCLUDE %2f1BEA%2fLCRMB_DL_OFI_OU01.
                    "/1BEA/CRMB_DL_OFI_O_COMPARE
INCLUDE %2f1BEA%2fLCRMB_DL_OFI_OU02.
                    "/1BEA/CRMB_DL_OFI_O_CREATE
INCLUDE %2f1BEA%2fLCRMB_DL_OFI_OU03.
                    "/1BEA/CRMB_DL_OFI_O_DERIVE
INCLUDE %2f1BEA%2fLCRMB_DL_OFI_OU04.
                    "/1BEA/CRMB_DL_OFI_O_IC_CHECK
