*****************************************************************
*   THIS FILE IS GENERATED BY THE FUNCTION LIBRARY.             *
*   NEVER CHANGE IT MANUALLY, PLEASE!                           *
*****************************************************************
INCLUDE %2f1BEA%2fLCRMB_BD_TXT_OU01.
                    "/1BEA/CRMB_BD_TXT_O_CREATE_EXT
INCLUDE %2f1BEA%2fLCRMB_BD_TXT_OU02.
                    "/1BEA/CRMB_BD_TXT_O_HD_COPY
INCLUDE %2f1BEA%2fLCRMB_BD_TXT_OU03.
                    "/1BEA/CRMB_BD_TXT_O_HD_CREATE
INCLUDE %2f1BEA%2fLCRMB_BD_TXT_OU04.
                    "/1BEA/CRMB_BD_TXT_O_HD_GET
INCLUDE %2f1BEA%2fLCRMB_BD_TXT_OU05.
                    "/1BEA/CRMB_BD_TXT_O_HD_PROVID
INCLUDE %2f1BEA%2fLCRMB_BD_TXT_OU06.
                    "/1BEA/CRMB_BD_TXT_O_HD_PUT
INCLUDE %2f1BEA%2fLCRMB_BD_TXT_OU07.
                    "/1BEA/CRMB_BD_TXT_O_HD_READ
INCLUDE %2f1BEA%2fLCRMB_BD_TXT_OU08.
                    "/1BEA/CRMB_BD_TXT_O_IT_COPY
INCLUDE %2f1BEA%2fLCRMB_BD_TXT_OU09.
                    "/1BEA/CRMB_BD_TXT_O_IT_CREATE
INCLUDE %2f1BEA%2fLCRMB_BD_TXT_OU10.
                    "/1BEA/CRMB_BD_TXT_O_IT_GET
INCLUDE %2f1BEA%2fLCRMB_BD_TXT_OU11.
                    "/1BEA/CRMB_BD_TXT_O_IT_PROVID
INCLUDE %2f1BEA%2fLCRMB_BD_TXT_OU12.
                    "/1BEA/CRMB_BD_TXT_O_IT_PUT
INCLUDE %2f1BEA%2fLCRMB_BD_TXT_OU13.
                    "/1BEA/CRMB_BD_TXT_O_IT_READ
INCLUDE %2f1BEA%2fLCRMB_BD_TXT_OU14.
                    "/1BEA/CRMB_BD_TXT_O_REFRESH
INCLUDE %2f1BEA%2fLCRMB_BD_TXT_OU15.
                    "/1BEA/CRMB_BD_TXT_O_SAVE
