*****************************************************************
*   THIS FILE IS GENERATED BY THE FUNCTION LIBRARY.             *
*   NEVER CHANGE IT MANUALLY, PLEASE!                           *
*****************************************************************
INCLUDE %2f1BEA%2fLCRMB_BD_MWC_OU01.
                    "/1BEA/CRMB_BD_MWC_O_1O_UPDATE
INCLUDE %2f1BEA%2fLCRMB_BD_MWC_OU02.
                    "/1BEA/CRMB_BD_MWC_O_FLOW
INCLUDE %2f1BEA%2fLCRMB_BD_MWC_OU03.
                    "/1BEA/CRMB_BD_MWC_O_VALIDATE
