*****************************************************************
*   THIS FILE IS GENERATED BY THE FUNCTION LIBRARY.             *
*   NEVER CHANGE IT MANUALLY, PLEASE!                           *
*****************************************************************
INCLUDE %2fSAPCND%2fLDD_DETERMINATIONU01.
                    "/SAPCND/DD_DETERMINE
