*****************************************************************
*   THIS FILE IS GENERATED BY THE FUNCTION LIBRARY.             *
*   NEVER CHANGE IT MANUALLY, PLEASE!                           *
*****************************************************************
INCLUDE %2fSAPCND%2fLGENERALU01.
                    "/SAPCND/GET_GLOBAL_PARAMETER
INCLUDE %2fSAPCND%2fLGENERALU02.
                    "/SAPCND/CN_TABLE_NAME_SET
INCLUDE %2fSAPCND%2fLGENERALU04.
                    "/SAPCND/CN_SCALE_NAME_SET
INCLUDE %2fSAPCND%2fLGENERALU06.
                    "/SAPCND/ADD_CONTEXT_LOG_ENTRY
INCLUDE %2fSAPCND%2fLGENERALU07.
                    "/SAPCND/DISPLAY_CONTEXT_LOG
INCLUDE %2fSAPCND%2fLGENERALU03.
                    "/SAPCND/GET_DET_MODULE_NAMES
