CONSTANTS:
  GC_PRC_PD_READONLY    TYPE C                  VALUE 'R',  "#EC *
  GC_PRC_PD_READWRIT    TYPE C                  VALUE 'U',  "#EC *
  GC_PRC_SHKZG_POS      TYPE PRCT_ITEM_SIGN     VALUE ' ',  "#EC *
  GC_PRC_SHKZG_NEG      TYPE PRCT_ITEM_SIGN     VALUE 'X',  "#EC *
  GC_SAVE_IMPLICITLY    TYPE PRCT_SAVE_IMPLICIT VALUE 'X',  "#EC *
  GC_GROUP_PROC         TYPE XFELD              VALUE 'X',  "#EC *
  GC_PRC_ERR_NO         TYPE BEA_PRICING_ERROR  VALUE ' ',  "#EC *
  GC_PRC_ERR_NO_NOTREL  TYPE BEA_PRICING_ERROR  VALUE 'N',  "#EC *
  GC_PRC_ERR_X          TYPE BEA_PRICING_ERROR  VALUE 'X',  "#EC *
  GC_PRC_ERR_F          TYPE BEA_PRICING_ERROR  VALUE 'F',  "#EC *
  GC_PRC_ERR_C          TYPE BEA_PRICING_ERROR  VALUE 'C',  "#EC *
  GC_PRC_STAT_OK        TYPE BEA_PRICING_STATUS VALUE ' ',  "#EC *
  GC_PRC_STAT_NOTREL    TYPE BEA_PRICING_STATUS VALUE 'N',  "#EC *
  GC_PRC_STAT_ERR       TYPE BEA_PRICING_STATUS VALUE 'A',  "#EC *
  GC_PRC_STAT_WARN      TYPE BEA_PRICING_STATUS VALUE 'B',  "#EC *
  GC_PRC_STAT_MAP       TYPE BEA_PRICING_STATUS VALUE 'C',  "#EC *
  GC_PRC_STAT_INTERR    TYPE BEA_PRICING_STATUS VALUE 'D',  "#EC *
  GC_PRC_STATISTIC_X    TYPE CHAR1              VALUE 'X',  "#EC *
  GC_PRC_STATISTIC_Y    TYPE CHAR1              VALUE 'Y',  "#EC *
  GC_PRC_COPY           TYPE BEA_BOOLEAN        VALUE ' ',  "#EC *
  GC_PRC_NOCOPY         TYPE BEA_BOOLEAN        VALUE 'X',  "#EC *
  GC_PRC_TRUE           TYPE XFELD              VALUE 'X'.  "#EC *
