CONSTANTS: BEGIN OF GC_PARTNER_PFT,                                    "#EC *

       UNDEFINDED                   TYPE COMT_PARTNER_PFT VALUE '0000',
       UNDEFINED                    TYPE COMT_PARTNER_PFT VALUE '0000',

       SOLD_TO                      TYPE COMT_PARTNER_PFT VALUE '0001',
       SHIP_TO                      TYPE COMT_PARTNER_PFT VALUE '0002',
       BILL_TO                      TYPE COMT_PARTNER_PFT VALUE '0003',
       PAYER                        TYPE COMT_PARTNER_PFT VALUE '0004',
       EMPLOYEE                     TYPE COMT_PARTNER_PFT VALUE '0005',
       CONTACT_PARTNER              TYPE COMT_PARTNER_PFT VALUE '0006',
       CONTACT_PERSON               TYPE COMT_PARTNER_PFT VALUE '0007',
       RESPONSIBLE                  TYPE COMT_PARTNER_PFT VALUE '0008',
       COMPETITOR                   TYPE COMT_PARTNER_PFT VALUE '0009',
       SALES_PARTNER                TYPE COMT_PARTNER_PFT VALUE '0010',
       BIDDER                       TYPE COMT_PARTNER_PFT VALUE '0011',
       VENDOR                       TYPE COMT_PARTNER_PFT VALUE '0012',
       DEMANDER                     TYPE COMT_PARTNER_PFT VALUE '0013',
       PORTAL_SUPPLIER              TYPE COMT_PARTNER_PFT VALUE '0014',
       BILLING_UNIT                 TYPE COMT_PARTNER_PFT VALUE '0015',
       EXEC_SERVICE_ORG             TYPE COMT_PARTNER_PFT VALUE '0016',
       INBOUND_DELIVERY_POINT       TYPE COMT_PARTNER_PFT VALUE '0017',
       OUTBOUND_DELIVERY_POINT      TYPE COMT_PARTNER_PFT VALUE '0018',
       RELEASE_PARTNER              TYPE COMT_PARTNER_PFT VALUE '0019',
       ALTERNATIVE_PAYER            TYPE COMT_PARTNER_PFT VALUE '0020',
       PAYEE                        TYPE COMT_PARTNER_PFT VALUE '0021',
       CORRESPONDENCE_RECIPIENT     TYPE COMT_PARTNER_PFT VALUE '0022',
       DUNNING_RECIPIENT            TYPE COMT_PARTNER_PFT VALUE '0023',
       PRICING_HIERARCHY            TYPE COMT_PARTNER_PFT VALUE '0024',
       EXECUTING_SERVICE_EMPLOYEE   TYPE COMT_PARTNER_PFT VALUE '0025',
       VENDOR_PROPOSAL              TYPE COMT_PARTNER_PFT VALUE '0026',
       BUYING_CENTER                TYPE COMT_PARTNER_PFT VALUE '0027',
       RESPONSIBLE_AT_PARTNER       TYPE COMT_PARTNER_PFT VALUE '0032',
       END_CUSTOMER                 TYPE COMT_PARTNER_PFT VALUE '0033',
       RESPONSIBLE_ORGANISATION     TYPE COMT_PARTNER_PFT VALUE '0034',

       EXECUTING_CALL_CENTER        TYPE COMT_PARTNER_PFT VALUE '0028',
       EXECUTING_INTERACTION_CENTER TYPE COMT_PARTNER_PFT VALUE '0028',

       collateral_provider          TYPE COMT_PARTNER_PFT VALUE '0029',
       guarantor                    TYPE COMT_PARTNER_PFT VALUE '0029',

       SOLD_FROM                    TYPE COMT_PARTNER_PFT VALUE '0030',
       LOCATION                     TYPE COMT_PARTNER_PFT VALUE '0031',
       VALIDATED_ACCOUNT            TYPE COMT_PARTNER_PFT VALUE '0062',
       TAX_ACCOUNT                  TYPE COMT_PARTNER_PFT VALUE '0063'.

CONSTANTS: END OF GC_PARTNER_PFT.
*
