*----------------------------------------------------------------------*
*   INCLUDE CTRLDEFN                                                   *
*----------------------------------------------------------------------*

* include for image controls
INCLUDE SIMAGECONTROLCLASSDEF.
INCLUDE SIMAGECONTROLCLASSIMPL.

DATA IMAGE_NAME(20) TYPE C VALUE 'JOBWIZ'.
DATA IMG_CRL TYPE REF TO C_IMAGE_CONTROL.
DATA URL(255) TYPE C.
DATA PIC_DATA LIKE W3MIME OCCURS 0.
DATA PIC_SIZE TYPE I.

DATA QUERY_TABLE LIKE W3QUERY OCCURS 1 WITH HEADER LINE.
DATA HTML_TABLE LIKE W3HTML OCCURS 1.
DATA RETURN_CODE LIKE  W3PARAM-RET_CODE.
DATA CONTENT_TYPE LIKE  W3PARAM-CONT_TYPE.
DATA CONTENT_LENGTH LIKE  W3PARAM-CONT_LEN.
