TYPE-POOL F4TYP .

TYPES: BEGIN OF F4TYP_MC_MULT_OBJ_IDS,
          PSEUDO_ID LIKE F4MCHLP-MCID,
          OBJ_DESCRIPTION LIKE F4MCHLP,
       END OF F4TYP_MC_MULT_OBJ_IDS.

TYPES: F4TYP_MULT_OBJ_ID TYPE F4TYP_MC_MULT_OBJ_IDS OCCURS 0.

TYPES: BEGIN OF F4TYP_MULT_OBJ_ID_RETURN,
         PSEUDO_ID LIKE F4MCHLP-MCID,
         RETURNVALUE LIKE RSMDY2,
       END OF F4TYP_MULT_OBJ_ID_RETURN.

TYPES: BEGIN OF F4TYP_HEAD_STRUC,
         TABNAME LIKE HELP_INFO-TABNAME,
         FIELDNAME LIKE HELP_INFO-FIELDNAME,
         HEAD_TEXT LIKE SHSTRUC-KEYWORD,
       END OF F4TYP_HEAD_STRUC.

TYPES: F4TYP_HEADING_TAB TYPE F4TYP_HEAD_STRUC OCCURS 0.
