*****************************************************************
*   THIS FILE IS GENERATED BY THE FUNCTION LIBRARY.             *
*   NEVER CHANGE IT MANUALLY, PLEASE!                           *
*****************************************************************
INCLUDE LBEA_AL_UU01.
                    "BEA_AL_U_SHOW
INCLUDE LBEA_AL_UU02.
                    "BEA_AL_U_SHOW_MULTI
