*****************************************************************
*   THIS FILE IS GENERATED BY THE FUNCTION LIBRARY.             *
*   NEVER CHANGE IT MANUALLY, PLEASE!                           *
*****************************************************************
INCLUDE LBEA_CRP_OU01.
                    "BEA_CRP_O_GETLIST
INCLUDE LBEA_CRP_OU02.
                    "BEA_CRP_O_SAVE
INCLUDE LBEA_CRP_OU03.
                    "BEA_CRP_O_CREATE
INCLUDE LBEA_CRP_OU04.
                    "BEA_CRP_O_REFRESH
INCLUDE LBEA_CRP_OU05.
                    "BEA_CRP_O_GET
INCLUDE LBEA_CRP_OU06.
                    "BEA_CRP_O_GETDETAIL
