*****************************************************************
*   THIS FILE IS GENERATED BY THE FUNCTION LIBRARY.             *
*   NEVER CHANGE IT MANUALLY, PLEASE!                           *
*****************************************************************
INCLUDE LBEA_AUT_OU03.
                    "BEA_AUT_O_REFRESH
INCLUDE LBEA_AUT_OU05.
                    "BEA_AUT_O_CHECK_ALL
INCLUDE LBEA_AUT_OU01.
                    "BEA_AUTH_RANGES
INCLUDE LBEA_AUT_OU02.
                    "BEA_AUT_O_CHECK_GEN
INCLUDE LBEA_AUT_OU04.
                    "BEA_ACE_NOTIFY
INCLUDE LBEA_AUT_OU06.
                    "BEA_AUT_ACE_CHECK_REQUIRED
