FUNCTION-POOL BEA_BTY_O.               "MESSAGE-ID ..

INCLUDE BEA_BASICS_CON.

DATA  GT_BTY_D TYPE BEAT_BTY_WRK.
DATA  GS_BTY   TYPE BEAS_BTY_WRK.
DATA  GT_NAMETAB TYPE DFIES OCCURS 0.
INCLUDE LSVIMDAT                                . "general data decl.
DATA  GV_APPL TYPE BEF_APPL.
