*****************************************************************
*   THIS FILE IS GENERATED BY THE FUNCTION LIBRARY.             *
*   NEVER CHANGE IT MANUALLY, PLEASE!                           *
*****************************************************************
INCLUDE LBEA_AL_OU08.
                    "BEA_AL_O_CREATE
INCLUDE LBEA_AL_OU09.
                    "BEA_AL_O_SAVE
INCLUDE LBEA_AL_OU07.
                    "BEA_AL_O_GETLIST
INCLUDE LBEA_AL_OU01.
                    "BEA_AL_O_REFRESH
INCLUDE LBEA_AL_OU05.
                    "BEA_AL_O_GETBUFFER
INCLUDE LBEA_AL_OU02.
                    "BEA_AL_O_EXTNUMBER_FILL
INCLUDE LBEA_AL_OU03.
                    "BEA_AL_O_MSGS_ADD
INCLUDE LBEA_AL_OU04.
                    "BEA_AL_O_ADDMSGS
INCLUDE LBEA_AL_OU06.
                    "BEA_AL_O_GETMSGS
INCLUDE LBEA_AL_OU10.
                    "BEA_AL_O_REFMSGS
INCLUDE LBEA_AL_OU11.
                    "BEA_AL_O_DELETE
INCLUDE LBEA_AL_OU12.
                    "BEA_AL_O_SAVE_MULTI
