*****************************************************************
*   THIS FILE IS GENERATED BY THE FUNCTION LIBRARY.             *
*   NEVER CHANGE IT MANUALLY, PLEASE!                           *
*****************************************************************
INCLUDE LBEA_BTY_OU01.
                    "BEA_BTY_O_GETDETAIL
INCLUDE LBEA_BTY_OU02.
                    "BEA_BTY_O_GET_DESCRIPTION
INCLUDE LBEA_BTY_OU03.
                    "BEA_BTY_O_GETLIST
