*****************************************************************
*   THIS FILE IS GENERATED BY THE FUNCTION LIBRARY.             *
*   NEVER CHANGE IT MANUALLY, PLEASE!                           *
*****************************************************************
INCLUDE LBEA_BASICSU01.
                    "BEA_USER_TRANSLATE_NAME_TO_ID
INCLUDE LBEA_BASICSU02.
                    "BEA_DATE_FROMTO_CONVERT2_RANGE
INCLUDE LBEA_BASICSU03.
                    "BEA_RESTRICT_SELECTION
INCLUDE LBEA_BASICSU04.
                    "BEA_F4_BATCH_SERVER_NAME
INCLUDE LBEA_BASICSU06.
                    "BEA_BATCH_SERVER_INFO_GETLIST
INCLUDE LBEA_BASICSU07.
                    "BEA_CONVERT_NUM_RANGE
