*****************************************************************
*   THIS FILE IS GENERATED BY THE FUNCTION LIBRARY.             *
*   NEVER CHANGE IT MANUALLY, PLEASE!                           *
*****************************************************************
INCLUDE LSEU_BUFFER_MANAGEMENTU01.
                    "RS_TRDIR_SELECT
INCLUDE LSEU_BUFFER_MANAGEMENTU03.
                    "RS_TRDIR_UPDATE
