FUNCTION-POOL SLDB MESSAGE-ID DB.

TABLES: TRDIR.
TABLES: LDBD.
TYPE-POOLS SSCR.
TYPE-POOLS SYDB0.
TYPE-POOLS SYLDB.
TYPE-POOLS SLIS.

CONSTANTS CV_SUBTY_VIA_SELSCR TYPE X VALUE '04'.

* BINK100804 Anfang
INCLUDE RSDBCOM2.
* BINK100804 Ende

* ------------ Daten für RS_INT_SELSCREEN_VERSION_F4 ----------------- *
* ------------- und RS_SELSCREEN_VERSION_EXISTS ---------------------- *
* Feldbeschreibung der Tabellentabelle (RS_VALUES_BOX)
DATA BEGIN OF FIDESC_VERSION OCCURS 5.
  INCLUDE STRUCTURE RSVBFIDESC.
DATA END   OF FIDESC_VERSION.
* Merker: welches Datenbankprogramm wurde als letztes gelesen.
DATA: BEGIN OF  LAST_SAPDB,
        SAPDB LIKE TRDIR-NAME,
        NUMB_OF_VERSIONS TYPE I,
      END   OF  LAST_SAPDB.
* Für RS_VALUES_BOX: Versionen
DATA: BEGIN OF POPUP_VERSIONS OCCURS 10,
        VERSION LIKE TRDIR-TYPE,
        TEXT(50),
      END   OF POPUP_VERSIONS.

* Daten für SELTAB_2_SELOPTS
DATA G_SELTAB LIKE RSPARAMS OCCURS 50 WITH HEADER LINE.
DATA G_SELTAB_255 LIKE RSPARAMSL_255 OCCURS 50 WITH HEADER LINE.

DATA SELTAB_CURR LIKE SY-TABIX.

* Daten für SELSCREEN_ICONS_SUPPLY
DATA G_OPTIICONS LIKE RSOPTIICON OCCURS 20 WITH HEADER LINE.
