*****************************************************************
*   THIS FILE IS GENERATED BY THE FUNCTION LIBRARY.             *
*   NEVER CHANGE IT MANUALLY, PLEASE!                           *
*****************************************************************
INCLUDE LSLVC_FULLSCREENU01.
                    "REUSE_ALV_GRID_DISPLAY
INCLUDE LSLVC_FULLSCREENU02.
                    "REUSE_ALV_GRID_LAYOUT_INFO_GET
INCLUDE LSLVC_FULLSCREENU03.
                    "REUSE_ALV_GRID_LAYOUT_INFO_SET
INCLUDE LSLVC_FULLSCREENU04.
                    "REUSE_ALV_GRID_COMMENTARY_SET
INCLUDE LSLVC_FULLSCREENU05.
                    "REUSE_ALV_GRID_DISPLAY_LVC
INCLUDE LSLVC_FULLSCREENU06.
                    "GET_GLOBALS_FROM_SLVC_FULLSCR
INCLUDE LSLVC_FULLSCREENU07.
                    "REUSE_ALV_TREE_DISPLAY_OM
