*&---------------------------------------------------------------------*
*&  Include           RSXMIBAPI_MSG
*&---------------------------------------------------------------------*

* d023157     23.3.2007
* an own include file has been vreated, which only contains the
* definitions of the message numbers formerly in RSXMIBAPI

constants:

           xmi_messages               LIKE sy-msgid VALUE 'XM',
           msg_logon_gen              LIKE sy-msgno VALUE '9',
           msg_logon                  LIKE sy-msgno VALUE '010',
           msg_logoff_gen             LIKE sy-msgno VALUE '011',
           msg_logoff                 LIKE sy-msgno VALUE '012',
           msg_auditlevel_set         LIKE sy-msgno VALUE '013',
           msg_versions_get_gen       LIKE sy-msgno VALUE '014',
           msg_versions_get           LIKE sy-msgno VALUE '015',
           msg_version_check          LIKE sy-msgno VALUE '016',
           msg_interface_describe     LIKE sy-msgno VALUE '017',
           msg_logmsg_enter           LIKE sy-msgno VALUE '018',
           msg_log_select             LIKE sy-msgno VALUE '019',
           msg_message_formats_upload LIKE sy-msgno VALUE '020',
           msg_already_logged_on_gen  LIKE sy-msgno VALUE '021',
           msg_already_logged_on      LIKE sy-msgno VALUE '022',
           msg_unknown_interface      LIKE sy-msgno VALUE '023',
           msg_unknown_version        LIKE sy-msgno VALUE '024',
           msg_logon_denied_gen       LIKE sy-msgno VALUE '025',
           msg_logon_denied           LIKE sy-msgno VALUE '026',
           msg_not_logged_on_gen      LIKE sy-msgno VALUE '027',
           msg_not_logged_on          LIKE sy-msgno VALUE '028',
           msg_invalid_range          LIKE sy-msgno VALUE '029',
           msg_cant_select            LIKE sy-msgno VALUE '030',
           msg_cant_log               LIKE sy-msgno VALUE '031',
           msg_cant_upload            LIKE sy-msgno VALUE '032',
           msg_invalid_parameters     LIKE sy-msgno VALUE '033',
           msg_problem_detected       LIKE sy-msgno VALUE '034',
           msg_reorg_gen              LIKE sy-msgno VALUE '037',
           msg_reorg                  LIKE sy-msgno VALUE '035',
           msg_jobname_missing        LIKE sy-msgno VALUE '046',
           msg_jobid_missing          LIKE sy-msgno VALUE '047',
           msg_ext_user_missing       LIKE sy-msgno VALUE '048',
           msg_job_does_not_exist     LIKE sy-msgno VALUE '049',
           msg_progname_missing       LIKE sy-msgno VALUE '050',
           msg_no_archive_info        LIKE sy-msgno VALUE '051',
           msg_invalid_print_params   LIKE sy-msgno VALUE '052',
           msg_invalid_archive_params LIKE sy-msgno VALUE '053',
           msg_no_release_privileg    LIKE sy-msgno VALUE '054',
           msg_job_not_active         LIKE sy-msgno VALUE '055',
           msg_no_abort_privilege     LIKE sy-msgno VALUE '056',
           msg_no_job_found           LIKE sy-msgno VALUE '057',
           msg_targethost_missing     LIKE sy-msgno VALUE '058',
           msg_no_jobsteps            LIKE sy-msgno VALUE '059',
           msg_no_job_protocol        LIKE sy-msgno VALUE '060',
           msg_empty_job_protocol     LIKE sy-msgno VALUE '061',
           msg_step_count_missing     LIKE sy-msgno VALUE '062',
           msg_no_spoollist           LIKE sy-msgno VALUE '063',
           msg_privilege_missing      LIKE sy-msgno VALUE '064',
           msg_invalid_spoolid        LIKE sy-msgno VALUE '065',
           msg_no_immediate_start_poss LIKE sy-msgno VALUE '066',
           msg_no_resources_found     LIKE sy-msgno VALUE '067',
           msg_invalid_date_time      LIKE sy-msgno VALUE '068',
           msg_invalid_server_name    LIKE sy-msgno VALUE '069',
           msg_prog_has_no_variant    LIKE sy-msgno VALUE '070',
           msg_prog_does_not_exist    LIKE sy-msgno VALUE '071',
           msg_no_execute_privilege   LIKE sy-msgno VALUE '072',
           msg_prog_not_executable    LIKE sy-msgno VALUE '073',
           msg_no_variants_defined    LIKE sy-msgno VALUE '074',
           msg_invalid_select_option  LIKE sy-msgno VALUE '075',
           msg_select_param_missing   LIKE sy-msgno VALUE '076',
           msg_trace_before_call      LIKE sy-msgno VALUE '077',
           msg_select_jobname_missing  LIKE sy-msgno VALUE '078',
           msg_select_username_missing LIKE sy-msgno VALUE '079',
           msg_cant_del_in_jobtable    LIKE sy-msgno VALUE '080',
           msg_cant_del_joblog         LIKE sy-msgno VALUE '081',
           msg_problem_pred_succ       LIKE sy-msgno VALUE '082',
           msg_commit_failed           LIKE sy-msgno VALUE '083',
           msg_no_delete_privilege     LIKE sy-msgno VALUE '084',
           msg_job_running             LIKE sy-msgno VALUE '085',
           msg_interface_reorg         LIKE sy-msgno VALUE '086',
           msg_interface_reorg_gen     LIKE sy-msgno VALUE '087',
***** c5034979 XBP20 *****
           msg_parent_child_inconsistency  LIKE sy-msgno VALUE '088',
           msg_child_register_error    LIKE sy-msgno VALUE '089',
           msg_mask_error              LIKE sy-msgno VALUE '090',
           msg_param_missing           LIKE sy-msgno VALUE '091',
           msg_event_does_not_exist    LIKE sy-msgno VALUE '092',
           msg_event_raise_failed      LIKE sy-msgno VALUE '093',
           msg_job_confirmation_failed LIKE sy-msgno VALUE '094',
           msg_wrong_confirmation_type LIKE sy-msgno VALUE '095',
           msg_wrong_selection_par     LIKE sy-msgno VALUE '096',
           msg_parentchild_inactive    LIKE sy-msgno VALUE '097',
           msg_interception_inactive   LIKE sy-msgno VALUE '098',
           msg_wrong_counter           LIKE sy-msgno VALUE '099',
           msg_wrong_printer_name      LIKE sy-msgno VALUE '122',
           msg_selection_finished      LIKE sy-msgno VALUE '101',

msg_cant_enq_job                     LIKE sy-msgno VALUE '194',
msg_cant_read_jobdata                LIKE sy-msgno VALUE '195',
msg_cant_release_job                 LIKE sy-msgno VALUE '196',
msg_cant_set_jobstatus_in_db         LIKE sy-msgno VALUE '197',
msg_cant_start_job_immediately       LIKE sy-msgno VALUE '198',
msg_cant_update_jobdata              LIKE sy-msgno VALUE '199',
msg_eventcnt_generation_error        LIKE sy-msgno VALUE '200',
msg_invalid_dialog_type              LIKE sy-msgno VALUE '201',
msg_invalid_new_jobdata              LIKE sy-msgno VALUE '202',
msg_invalid_new_jobstatus            LIKE sy-msgno VALUE '203',
msg_invalid_startdate                LIKE sy-msgno VALUE '204',
msg_job_edit_failed                  LIKE sy-msgno VALUE '205',
msg_job_modify_canceled              LIKE sy-msgno VALUE '206',
msg_job_not_modifiable_anymore       LIKE sy-msgno VALUE '207',
msg_nothing_to_do                    LIKE sy-msgno VALUE '208',
msg_no_batch_on_target_host          LIKE sy-msgno VALUE '209',
msg_no_batch_server_found            LIKE sy-msgno VALUE '210',
msg_no_batch_wp_for_jobclass         LIKE sy-msgno VALUE '211',
msg_no_modify_privilege_given        LIKE sy-msgno VALUE '212',
msg_no_release_privilege_given       LIKE sy-msgno VALUE '213',
msg_no_startdate_no_release          LIKE sy-msgno VALUE '214',
msg_target_host_not_defined          LIKE sy-msgno VALUE '215',
msg_tgt_host_chk_has_failed          LIKE sy-msgno VALUE '215',  "????
msg_invalid_targetgroup              LIKE sy-msgno VALUE '216',
msg_conflicting_targets              LIKE sy-msgno VALUE '217',
*msg_job_doesnt_have_steps            LIKE sy-msgno VALUE '218',
msg_wrong_step_type                  LIKE sy-msgno VALUE '219',
msg_job_doesnt_have_this_step        LIKE sy-msgno VALUE '220',
msg_cannot_get_priarc_params         LIKE sy-msgno VALUE '221',
msg_cannot_read_job                  LIKE sy-msgno VALUE '222',
msg_cannot_modify_job                LIKE sy-msgno VALUE '223',
msg_wrong_step_number                LIKE sy-msgno VALUE '224',
msg_error_modifying_worktable        LIKE sy-msgno VALUE '225',
msg_empty                            LIKE sy-msgno VALUE '226',
msg_job_nosteps                      LIKE sy-msgno VALUE '227',
msg_jobcount_missing                 LIKE sy-msgno VALUE '228',
msg_invalid_target                   LIKE sy-msgno VALUE '229',
msg_error_reading_worktable          LIKE sy-msgno VALUE '230',
msg_delete_line_error                LIKE sy-msgno VALUE '231',
msg_no_step_info                     LIKE sy-msgno VALUE '232',
msg_wrong_action                     LIKE sy-msgno VALUE '233',
msg_no_change_authority              LIKE sy-msgno VALUE '234',
msg_invalid_jobclass                 LIKE sy-msgno VALUE '235',
msg_wrong_client                     LIKE sy-msgno VALUE '236',
msg_cant_create_rec_object           LIKE sy-msgno VALUE '237',
msg_spool_selection_empty            LIKE sy-msgno VALUE '238',

msg_variant_does_not_exist           LIKE sy-msgno VALUE '239',
msg_variant_already_exists           LIKE sy-msgno VALUE '241',
msg_no_variant_specified             LIKE sy-msgno VALUE '242',
msg_error_in_function                LIKE sy-msgno VALUE '243',
msg_no_variant_text_specified        LIKE sy-msgno VALUE '244',

msg_error_in_function_1              LIKE sy-msgno VALUE '246',
msg_error_in_form                    LIKE sy-msgno VALUE '247',

* the purpose of the dummy message is, that it is converted
* to a 'real' message later on in the coding
msg_dummy                           like sy-msgno VALUE '245',

** Eventhistory Messages:
msg_invalid_evt_select_state        TYPE symsgno VALUE '250',
msg_invalid_from_timestamp          TYPE symsgno VALUE '251',
msg_invalid_to_timestamp            TYPE symsgno VALUE '252',
msg_invalid_evt_confirm_action      TYPE symsgno VALUE '253',

** more messages for precise XBP error handling

msg_no_authority                    TYPE symsgno VALUE '260',
msg_job_lock_failed                 TYPE symsgno VALUE '261',
msg_variant_does_not_exist_2        type symsgno VALUE '262',
msg_xmi_error_info                  type symsgno VALUE '263',
msg_cant_release_job_2              type symsgno VALUE '264',
msg_xmi_error_info_continued        type symsgno VALUE '265',
msg_correcting_state_failed         type symsgno VALUE '266',
msg_fact_cal_does_not_exist         type symsgno VALUE '267',
msg_cant_return_recipient           type symsgno VALUE '270',
msg_cannot_create_pdf               type symsgno VALUE '271',
msg_log_too_large                   type symsgno VALUE '272',
msg_variable_text                   type symsgno VALUE '300'.
