TYPE-POOL SP01R.
TYPE-POOLS SLIS.
TYPES: BEGIN OF SP01R_VIEW.
         INCLUDE STRUCTURE TSP01_SP0R.
TYPES:   CHECKBOX(1) TYPE C,
         SELECTED(1) TYPE C,
         DELETED(1) TYPE C,
         SINDEX LIKE SY-TABIX,
         COLOR_INFO TYPE SLIS_T_SPECIALCOL_ALV,
       END OF SP01R_VIEW.

TYPES: SP01R_TVIEW TYPE SP01R_VIEW OCCURS 1.

TYPES: BEGIN OF SP01R_ID,
         ID LIKE TSP01-RQIDENT.
         INCLUDE STRUCTURE ALSYSID.
TYPES: END OF SP01R_ID.
TYPES: SP01R_ID_LIST TYPE SP01R_ID OCCURS 10.
TYPES: BEGIN OF SP01R_PJID,
         ID LIKE TSP02-PJIDENT,
         NUM LIKE TSP02-PJNUMMER.
         INCLUDE STRUCTURE ALSYSID.
TYPES: END OF SP01R_PJID.
TYPES: SP01R_PJID_LIST TYPE SP01R_PJID OCCURS 10.

TYPES: BEGIN OF SP01R_OVIEW.
         INCLUDE STRUCTURE TSP02_SP0R.
TYPES:   CHECKBOX(1) TYPE C,
         SELECTED(1) TYPE C,
         SINDEX LIKE SY-TABIX,
         COLOR_INFO TYPE SLIS_T_SPECIALCOL_ALV,
       END OF SP01R_OVIEW.

TYPES: SP01R_TOVIEW TYPE SP01R_OVIEW OCCURS 1,
       SP01R_TSP01 TYPE TSP01SYS OCCURS 1,
       SP01R_TSP02 TYPE TSP02SYS OCCURS 1.


TYPES: SP01R_DATA_SET LIKE RSPO_DS.
TYPES: SP01R_DATA_SET2 LIKE RSPO_DS2.
TYPES: SP01R_DATA_SET_T TYPE SP01R_DATA_SET OCCURS 1.
TYPES: SP01R_DATA_SET2_T TYPE SP01R_DATA_SET2 OCCURS 1.

TYPES: SP01R_DATA_SETx LIKE RSPO_DSx.
TYPES: SP01R_DATA_SETx2 LIKE RSPO_DSx2.
TYPES: SP01R_DATA_SETx_T TYPE SP01R_DATA_SETx OCCURS 1.
TYPES: SP01R_DATA_SETx2_T TYPE SP01R_DATA_SETx2 OCCURS 1.

TYPES: BEGIN OF SP01R_RANGE,
         starting,
         ending,
         count(10) type n,
         dis_from(10) type n,
         dis_to(10) type n,
         dis_scroll(10) type n,
       end of sp01r_range.
types: sp01r_trange type sp01r_range occurs 1.
