TYPE-POOL THFB .

TYPES:

thfb_bool(1) type x,
thfb_byte(1) type x,
THFB_CONTEXT_ID(40),
thfb_session_id(32),
thfb_w3c_context_id(128),
THFB_PLUGIN_NAME(10),
thfb_hostname(128),
thfb_service(32),
thfb_appl_info(100),
thfb_appl_hide(128) type x,
thfb_wall_appl(8),
thfb_wall_appl_key(32),
begin of thfb_wall_key,
  id type thfb_session_id,
  appl type thfb_wall_appl,
  appl_key type thfb_wall_appl_key,
end of thfb_wall_key,
thfb_wall_item(10),
begin of thfb_wall_result,
  key type thfb_wall_key,
  item type thfb_wall_item,
  item_len type i,
end of thfb_wall_result,
thfb_wall_result_set type thfb_wall_result occurs 0,

begin of thfb_virt_server,
  number type i,
  value(128),
end of thfb_virt_server,
thfb_virt_serv_tbl type thfb_virt_server occurs 0,

begin of thfb_check_result,
  line(255),
end of thfb_check_result,
thfb_check_result_tbl type thfb_check_result occurs 0,

BEGIN OF THFB_TRACE,
  ID TYPE I,
  WPTYPE(3),
  LEVEL(2),
  MAIN(1),
  DIAG(1),
  ABAP(1),
  DB(1),
  IPC(1),
  ROLL(1),
  PAGE(1),
  BATCH(1),
  ENQ(1),
  SPOOL(1),
  DYNP(1),
  DBSL(1),
  SNC(1),
  EM(1),
  DBG(1),
  NLS(1),
  VMC(1),
  ITS(1),
  ICF(1),
  RES1(1),
END OF THFB_TRACE,

BEGIN OF THFB_BLK,
  INDEX TYPE I,
  OWNER TYPE I,
  PID(20),
END OF THFB_BLK,

THFB_WPCA   TYPE THFB_BLK OCCURS 0,
THFB_APPCCA TYPE THFB_BLK OCCURS 0.
